/**
 * API Diagnostics Utility
 * Helps diagnose authentication and connection issues
 */

import api from './api';

/**
 * Check if the backend server is reachable
 */
export const checkServerConnection = async () => {
  try {
    const response = await fetch(import.meta.env.VITE_API_URL.replace('/api', '') + '/health', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json'
      }
    });
    
    if (response.ok) {
      return { success: true, message: 'Server is reachable' };
    } else {
      return { success: false, message: `Server returned status: ${response.status}` };
    }
  } catch (error) {
    return { 
      success: false, 
      message: `Cannot reach server: ${error.message}`,
      details: 'Please check if the backend server is running'
    };
  }
};

/**
 * Verify the current authentication token
 */
export const verifyAuthToken = async () => {
  try {
    const token = localStorage.getItem('authToken');
    
    if (!token) {
      return { 
        success: false, 
        message: 'No authentication token found',
        action: 'Please log in'
      };
    }
    
    // Try to verify token with backend
    const response = await api.get('/admin/verify-token');
    
    if (response.data.valid) {
      return { 
        success: true, 
        message: 'Token is valid',
        user: response.data.user
      };
    } else {
      return { 
        success: false, 
        message: 'Token is invalid',
        action: 'Please log in again'
      };
    }
  } catch (error) {
    if (error.response?.status === 401) {
      return { 
        success: false, 
        message: 'Token is expired or invalid',
        action: 'Please log in again'
      };
    } else if (error.response?.status === 403) {
      return { 
        success: false, 
        message: 'Token verification failed - possible signature mismatch',
        details: 'The token may have been generated by a different server instance',
        action: 'Please log in again'
      };
    } else {
      return { 
        success: false, 
        message: `Token verification failed: ${error.message}`,
        action: 'Please log in again'
      };
    }
  }
};

/**
 * Get diagnostic information about the current session
 */
export const getDiagnosticInfo = () => {
  const token = localStorage.getItem('authToken');
  const isLoggedIn = localStorage.getItem('isLoggedIn');
  const userType = localStorage.getItem('userType');
  const adminUser = localStorage.getItem('adminUser');
  const apiUrl = import.meta.env.VITE_API_URL;
  
  return {
    hasToken: !!token,
    tokenPreview: token ? `${token.substring(0, 20)}...` : 'None',
    isLoggedIn: isLoggedIn === 'true',
    userType: userType || 'None',
    hasUserData: !!adminUser,
    apiUrl: apiUrl,
    timestamp: new Date().toISOString()
  };
};

/**
 * Run full diagnostics
 */
export const runFullDiagnostics = async () => {
  console.log('🔍 Running API Diagnostics...');
  console.log('================================');
  
  // 1. Check diagnostic info
  const info = getDiagnosticInfo();
  console.log('📊 Session Info:', info);
  
  // 2. Check server connection
  console.log('\n🌐 Checking server connection...');
  const serverCheck = await checkServerConnection();
  console.log(serverCheck.success ? '✅' : '❌', serverCheck.message);
  if (serverCheck.details) console.log('   ', serverCheck.details);
  
  // 3. Verify token
  if (info.hasToken) {
    console.log('\n🔐 Verifying authentication token...');
    const tokenCheck = await verifyAuthToken();
    console.log(tokenCheck.success ? '✅' : '❌', tokenCheck.message);
    if (tokenCheck.details) console.log('   ', tokenCheck.details);
    if (tokenCheck.action) console.log('   Action:', tokenCheck.action);
  } else {
    console.log('\n⚠️  No authentication token found');
  }
  
  console.log('\n================================');
  console.log('Diagnostics complete');
  
  return {
    info,
    serverCheck,
    tokenCheck: info.hasToken ? await verifyAuthToken() : { success: false, message: 'No token' }
  };
};

/**
 * Clear all authentication data and redirect to login
 */
export const clearAuthAndRedirect = () => {
  console.log('🧹 Clearing authentication data...');
  
  localStorage.removeItem('authToken');
  localStorage.removeItem('isLoggedIn');
  localStorage.removeItem('adminUser');
  localStorage.removeItem('staffUser');
  localStorage.removeItem('userType');
  localStorage.removeItem('userPermissions');
  localStorage.removeItem('staffProfile');
  
  console.log('✅ Authentication data cleared');
  console.log('🔄 Redirecting to login...');
  
  window.location.href = '/login';
};
