import React, { createContext, useContext, useState, useEffect } from 'react';
import axios from 'axios';

// Apply theme immediately on module load to prevent flash
const applyThemeEarly = () => {
  const savedTheme = localStorage.getItem('appTheme');
  if (savedTheme) {
    try {
      const theme = JSON.parse(savedTheme);
      if (theme.mode === 'dark') {
        document.body.classList.add('dark-mode');
        document.documentElement.setAttribute('data-theme', 'dark');
      } else {
        document.body.classList.remove('dark-mode');
        document.documentElement.setAttribute('data-theme', 'light');
      }
    } catch (e) {
      console.error('Error applying early theme:', e);
    }
  }
};

// Call immediately when module loads
applyThemeEarly();

// Utility function to convert hex color to RGB
const hexToRgb = (hex) => {
  // Remove # if present
  hex = hex.replace(/^#/, '');
  
  // Handle 3-digit hex
  if (hex.length === 3) {
    hex = hex.split('').map(char => char + char).join('');
  }
  
  const result = /^([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16)
  } : null;
};

// Translations
const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    dashboardSubtitle: 'Overview of school management system',
    registration: 'Registration',
    registerStudent: 'Register Student',
    registerStaff: 'Register Staff',
    lists: 'Lists',
    students: 'Students',
    staff: 'Staff',
    academic: 'Academic',
    evaluation: 'Evaluation',
    markLists: 'Mark Lists',
    attendance: 'Attendance',
    createMarklist: 'Create Marklist',
    reportCard: 'Report Card',
    schedule: 'Schedule',
    post: 'Post',
    tasks: 'Tasks Dashboard',
    administration: 'Administration',
    communication: 'Communication',
    payments: 'Payments',
    settings: 'Settings',
    // Header
    search: 'Search...',
    myProfile: 'My Profile',
    logout: 'Logout',
    // Settings
    settingsTitle: 'Settings',
    settingsSubtitle: 'Manage your account and application preferences',
    profile: 'Profile',
    password: 'Password',
    theme: 'Theme',
    language: 'Language',
    branding: 'Branding',
    profileSettings: 'Profile Settings',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    saveProfile: 'Save Profile',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    themeSettings: 'Theme Settings',
    darkMode: 'Dark Mode',
    colorPresets: 'Color Presets',
    customColors: 'Custom Colors',
    primaryColor: 'Primary Color',
    secondaryColor: 'Secondary Color',
    preview: 'Preview',
    saveTheme: 'Save Theme',
    languageSettings: 'Language Settings',
    brandingSettings: 'Branding Settings',
    websiteIcon: 'Website Icon (Favicon)',
    uploadIcon: 'Upload Icon',
    // School Info
    schoolInfo: 'School Info',
    schoolLogo: 'School Logo',
    uploadLogo: 'Upload Logo',
    schoolDetails: 'School Details',
    schoolAddress: 'School Address',
    schoolPhone: 'Phone Number',
    schoolEmail: 'Email Address',
    academicYear: 'Academic Year',
    saveSchoolInfo: 'Save School Information',
    // Common
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    success: 'Success',
    error: 'Error',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    refresh: 'Refresh',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    all: 'All',
    noDataFound: 'No Data Found',
    actions: 'Actions',
    // Registration
    staffRegistration: 'Staff Registration',
    staffRegistrationDesc: 'Register new staff members to your organization',
    selectStaffType: 'Select Staff Type',
    supportiveStaff: 'Supportive Staff',
    supportiveStaffDesc: 'Guards, cleaners, drivers',
    administrativeStaff: 'Administrative Staff',
    administrativeStaffDesc: 'Directors, coordinators',
    teachers: 'Teachers',
    teachersDesc: 'Teaching staff members',
    availableForms: 'Available Forms',
    noFormsFound: 'No Forms Found',
    createFormFirst: 'Create a form structure first in the Form Builder section',
    addStaff: 'Add Staff',
    forms: 'Forms',
    active: 'Active',
    clickToAdd: 'Click to add new staff member',
    deleteForm: 'Delete Form',
    addStaffTo: 'Add Staff to',
    // Tasks
    tasksDashboard: 'Tasks Dashboard',
    tasksDesc: 'Track and manage your daily tasks',
    overallProgress: 'Overall Progress',
    completed: 'Completed',
    pending: 'Pending',
    viewDetails: 'View Details',
    taskCompleted: 'Completed',
    taskPending: 'Pending',
    // List Pages
    studentDirectory: 'Student Directory',
    studentDirectoryDesc: 'Manage all students and their documents',
    staffDirectory: 'Staff Directory',
    staffDirectoryDesc: 'Manage all staff members and their documents',
    searchByName: 'Search by name...',
    searchStudents: 'Search by name, guardian, phone...',
    searchStaff: 'Search by name, email, phone...',
    allGenders: 'All Genders',
    male: 'Male',
    female: 'Female',
    allTypes: 'All Types',
    totalStaff: 'Total Staff',
    categories: 'Categories',
    classes: 'Classes',
    noStudentsFound: 'No Students Found',
    noStaffFound: 'No Staff Found',
    tryAdjustingFilters: 'Try adjusting your search or filters',
    // Dashboard
    totalStudents: 'Total Students',
    attendanceRate: 'Attendance Rate',
    feeCollectionRate: 'Fee Collection Rate',
    vsLastMonth: 'vs last month',
    vsYesterday: 'vs yesterday',
    attendanceTrend: 'Attendance Trend',
    enrollmentTrend: 'Enrollment Trend',
    financialOverview: 'Financial Overview',
    last30Days: 'Last 30 days',
    thisAcademicYear: 'This academic year',
    currentMonth: 'Current month',
    chartPlaceholder: 'Chart visualization will be implemented here',
    recentActivity: 'Recent Activity',
    latestActions: 'Latest actions in the system',
    upcomingEvents: 'Upcoming Events',
    scheduledEvents: 'Scheduled exams and events',
    noRecentActivity: 'No recent activity',
    noUpcomingEvents: 'No upcoming events',
    lastUpdated: 'Last updated',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    documents: 'Documents',
    document: 'Document',
    basicInformation: 'Basic Information',
    loginCredentials: 'Login Credentials',
    studentAccount: 'Student Account',
    guardianAccount: 'Guardian Account',
    username: 'Username',
    documentsAndFiles: 'Documents & Files',
    download: 'Download',
    age: 'Age',
    guardian: 'Guardian',
    phone: 'Phone',
    email: 'Email',
    role: 'Role',
    department: 'Department',
    employmentType: 'Employment Type',
    fullTime: 'Full-time',
    partTime: 'Part-time',
    // Schedule
    scheduleDashboard: 'Schedule Dashboard',
    scheduleDesc: 'Manage class schedules and timetables',
    timetable: 'Timetable',
    createSchedule: 'Create Schedule',
    viewSchedule: 'View Schedule',
    // Mark List
    markListView: 'Mark List View',
    markListDesc: 'View and manage student marks',
    subject: 'Subject',
    marks: 'Marks',
    grade: 'Grade',
    total: 'Total',
    average: 'Average',
    // Evaluation
    evaluationTitle: 'Evaluation',
    evaluationDesc: 'Evaluate student performance',
    // Attendance
    attendanceView: 'Attendance View',
    attendanceDesc: 'Track student attendance',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    // Communication
    communicationTitle: 'Communication',
    communicationDesc: 'Send messages and announcements',
    sendMessage: 'Send Message',
    announcements: 'Announcements',
    // Profile Pages
    posts: 'Posts',
    evaluations: 'Evaluations',
    messages: 'Messages',
    profileInformation: 'Profile Information',
    accountInformation: 'Account Information',
    back: 'Back',
    fillForm: 'Fill Form',
    viewReport: 'View Report',
    inProgress: 'In Progress',
    noEvaluations: 'No evaluations assigned',
    noPosts: 'No posts yet',
    noMessages: 'No messages',
    // Attendance specific
    markAttendance: 'Mark Attendance',
    viewAttendanceMode: 'View Attendance',
    permission: 'Permission',
    saveAttendance: 'Save Attendance',
    createWeek: 'Create Week',
    selectWeek: 'Select Week',
    currentWeek: 'Current Week',
    nextWeek: 'Next Week',
    // Guardian/Ward specific
    wards: 'Wards',
    selectWard: 'Select Ward',
    wardAttendance: 'Ward Attendance',
    selectPeriod: 'Select Period',
    attendanceRecord: 'Attendance Record',
    // Class/Teacher specific
    classComm: 'Class',
    marklist: 'Mark List',
    mySchedule: 'My Schedule',
    // Dark mode
    darkModeOn: 'Dark mode is on',
    darkModeOff: 'Dark mode is off',
    settingsInfo: 'Your preferences are saved automatically and will be remembered next time you log in.',
    // Navigation - Additional
    evaluationBook: 'Evaluation Book',
    evalBookReports: 'Eval Book Reports',
    evalBookAssignments: 'Eval Book Assignments',
    subAccounts: 'Sub-Accounts',
    classTeachers: 'Class Teachers',
    // Admin Sub-Accounts
    adminSubAccounts: 'Admin Sub-Accounts',
    createSubAccount: 'Create Sub-Account',
    editSubAccount: 'Edit Sub-Account',
    deleteSubAccount: 'Delete Sub-Account',
    searchByNameEmailUsername: 'Search by name, email, or username...',
    noSubAccountsCreated: 'No sub-accounts created yet',
    noAccountsMatchSearch: 'No accounts match your search',
    permissions: 'Permissions',
    permissionsCount: 'permissions',
    status: 'Status',
    inactive: 'Inactive',
    activate: 'Activate',
    deactivate: 'Deactivate',
    name: 'Name',
    nameRequired: 'Name is required',
    emailRequired: 'Email is required',
    invalidEmailFormat: 'Invalid email format',
    usernameRequired: 'Username is required',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 6 characters',
    leaveBlankToKeepCurrent: 'leave blank to keep current',
    enterFullName: 'Enter full name',
    enterEmailAddress: 'Enter email address',
    enterUsername: 'Enter username',
    enterPassword: 'Enter password',
    enterNewPassword: 'Enter new password',
    accountCreatedSuccess: 'Account created successfully',
    accountUpdatedSuccess: 'Account updated successfully',
    accountDeletedSuccess: 'Account deleted successfully',
    failedToLoadSubAccounts: 'Failed to load sub-accounts',
    failedToSaveAccount: 'Failed to save account',
    failedToDeleteAccount: 'Failed to delete account',
    failedToToggleStatus: 'Failed to toggle status',
    usernameAlreadyExists: 'Username already exists',
    emailAlreadyExists: 'Email already exists',
    confirmDeleteAccount: 'Are you sure you want to delete',
    actionCannotBeUndone: 'This action cannot be undone.',
    saving: 'Saving...',
    create: 'Create',
    update: 'Update',
    // Create Staff Account
    createStaffAccount: 'Create School Staff Account',
    phoneNumber: 'Phone Number',
    gender: 'Gender',
    selectGender: 'Select gender',
    other: 'Other',
    selectRole: 'Select role',
    teacher: 'Teacher',
    admin: 'Admin',
    librarian: 'Librarian',
    principal: 'Principal',
    counselor: 'Counselor',
    selectDepartment: 'Select department',
    science: 'Science',
    english: 'English',
    mathematics: 'Mathematics',
    history: 'History',
    it: 'IT',
    hr: 'HR',
    passwordMinLength8: 'Password must be at least 8 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    profilePicture: 'Profile Picture',
    optional: 'Optional',
    chooseFile: 'Choose File',
    createAccount: 'Create Account',
    reset: 'Reset',
    creating: 'Creating...',
    staffAccountCreatedSuccess: 'Staff account created successfully!',
    required: 'required',
    // Guardian Directory
    guardianDirectory: 'Guardian Directory',
    guardianDirectoryDesc: 'View and manage all guardians',
    guardians: 'Guardians',
    searchGuardians: 'Search guardians...',
    noGuardiansFound: 'No guardians found',
    associatedStudents: 'Associated Students',
    contactInformation: 'Contact Information',
    relation: 'Relation',
    // Evaluation Book
    evaluationInbox: 'Evaluation Inbox',
    evaluationInboxDesc: 'Review and respond to your ward\'s daily evaluations',
    pendingResponse: 'Pending Response',
    responded: 'Responded',
    noEvaluationsYet: 'No Evaluations',
    noEvaluationsDesc: 'You don\'t have any evaluations to review yet.',
    tapToAddFeedback: 'Tap to add your feedback',
    allWards: 'All Wards',
    // Evaluation Book Reports
    evaluationBookReports: 'Evaluation Book Reports',
    evaluationBookReportsDesc: 'View all evaluation reports across the school',
    totalEvaluations: 'Total Evaluations',
    pendingResponses: 'Pending Responses',
    responseRate: 'Response Rate',
    filters: 'Filters',
    startDate: 'Start Date',
    endDate: 'End Date',
    allClasses: 'All Classes',
    searchStudent: 'Search student...',
    clearFilters: 'Clear Filters',
    noReportsFound: 'No reports found',
    adjustFiltersOrWait: 'Adjust your filters or wait for evaluations to be created',
    evaluationData: 'Evaluation Data',
    guardianFeedback: 'Guardian Feedback',
    submitted: 'Submitted',
    // Teacher Assignment
    teacherAssignments: 'Teacher Assignments',
    teacherAssignmentsDesc: 'Assign teachers to classes for the Evaluation Book system',
    newAssignment: 'New Assignment',
    selectTeacher: 'Select a teacher...',
    selectClass: 'Select a class...',
    assignTeacher: 'Assign Teacher',
    assigning: 'Assigning...',
    teacherAssignedSuccess: 'Teacher assigned successfully',
    assignmentRemoved: 'Assignment removed',
    removeAssignment: 'Remove this assignment?',
    noAssignmentsYet: 'No assignments yet',
    assignTeachersAbove: 'Assign teachers to classes using the form above',
    teacherCount: 'teacher(s)',
    // Class Teacher Assignment
    classTeacherAssignment: 'Class Teacher Assignment',
    classTeacherAssignmentDesc: 'Assign teachers to classes for attendance management',
    assignClassTeacher: 'Assign Class Teacher',
    selectTeacherLabel: 'Select Teacher:',
    selectClassLabel: 'Select Class:',
    assign: 'Assign',
    currentAssignments: 'Current Assignments',
    noClassTeachersAssigned: 'No class teachers assigned yet',
    removeClassTeacher: 'Remove class teacher from',
    teacherUnassigned: 'Teacher unassigned from',
    assigned: 'Assigned',
    unassignedClasses: 'Unassigned Classes',
    // Create Attendance
    createAttendance: 'Create Attendance',
    createAttendanceDesc: 'Create and manage attendance for any class',
    createNewWeek: 'Create New Week',
    editExisting: 'Edit Existing',
    classLabel: 'Class:',
    weekStartMonday: 'Week Start (Monday):',
    selectWeekLabel: 'Select Week:',
    selectWeekOption: '-- Select Week --',
    createAttendanceBtn: 'Create Attendance',
    saveAttendanceBtn: 'Save Attendance',
    existingAttendanceWeeks: 'Existing Attendance Weeks for',
    loadingAttendanceData: 'Loading attendance data...',
    noAttendanceData: 'No attendance data',
    selectWeekToEdit: 'Select a week to edit attendance',
    quickMarkAll: 'Quick mark all:',
    studentName: 'Student Name',
    presentP: 'Present (P)',
    absentA: 'Absent (A)',
    lateL: 'Late (L)',
    permissionE: 'Permission (E)',
    failedToFetchClasses: 'Failed to fetch classes',
    pleaseSelectClassAndWeek: 'Please select a class and week start date',
    noAttendanceDataToSave: 'No attendance data to save',
    failedToCreateAttendance: 'Failed to create attendance',
    failedToSaveAttendance: 'Failed to save attendance'
  },
  om: {
    dashboard: 'Daashboordii',
    registration: 'Galmee',
    registerStudent: 'Barataa Galmeessi',
    registerStaff: 'Hojjetaa Galmeessi',
    lists: 'Tarreewwan',
    students: 'Barattootaa',
    staff: 'Hojjettootaa',
    academic: 'Barnootaa',
    evaluation: 'Madaallii',
    markLists: 'Tarree Qabxii',
    attendance: 'Argama',
    createMarklist: 'Tarree Qabxii Uumi',
    reportCard: 'Kaardii Gabaasaa',
    schedule: 'Sagantaa',
    post: 'Maxxansa',
    // Common
    save: 'Olkaa\'i',
    cancel: 'Haqi',
    loading: 'Fe\'aa jira...',
    success: 'Milkaa\'e',
    error: 'Dogoggora',
    delete: 'Haqi',
    edit: 'Gulaali',
    view: 'Ilaali',
    refresh: 'Haaromsi',
    previous: 'Duraa',
    next: 'Itti Aanee',
    page: 'Fuula',
    of: 'keessaa',
    all: 'Hunda',
    noDataFound: 'Deetaan Hin Argamne',
    actions: 'Gocha',
    // Registration
    staffRegistration: 'Galmee Hojjettootaa',
    staffRegistrationDesc: 'Hojjettoota haaraa dhaabbata keessanitti galmeessaa',
    selectStaffType: 'Gosa Hojjetaa Filadhu',
    supportiveStaff: 'Hojjettoota Deeggarsa',
    supportiveStaffDesc: 'Eegdota, qulqulleessitoota, konkolaachiftoota',
    administrativeStaff: 'Hojjettoota Bulchiinsaa',
    administrativeStaffDesc: 'Daayirektaroota, qindeessitoota',
    teachers: 'Barsiisota',
    teachersDesc: 'Miseensota barsiisaa',
    availableForms: 'Unkaawwan Jiran',
    noFormsFound: 'Unkaawwan Hin Argamne',
    createFormFirst: 'Dursa caasaa unkaa kutaa Ijaarsa Unkaa keessatti uumi',
    addStaff: 'Hojjetaa Dabali',
    forms: 'Unkaawwan',
    active: 'Hojii irra',
    clickToAdd: 'Hojjetaa haaraa dabaluuf cuqaasi',
    deleteForm: 'Unkaa Haqi',
    addStaffTo: 'Hojjetaa Dabali',
    // Tasks
    tasksDashboard: 'Daashboordii Hojii',
    tasksDesc: 'Hojii guyyaa guyyaa kee hordofi fi bulchi',
    overallProgress: 'Guddina Waliigalaa',
    completed: 'Xumurameera',
    pending: 'Eeggataa',
    viewDetails: 'Bal\'inaan Ilaali',
    taskCompleted: 'Xumurameera',
    taskPending: 'Eeggataa',
    tasks: 'Daashboordii Hojii',
    administration: 'Bulchiinsa',
    communication: 'Quunnamtii',
    payments: 'Kaffaltii',
    settings: 'Qindaa\'ina',
    search: 'Barbaadi...',
    myProfile: 'Piroofaayilii Koo',
    logout: 'Ba\'i',
    settingsTitle: 'Qindaa\'ina',
    settingsSubtitle: 'Herrega fi filannoo appii kee bulchi',
    profile: 'Piroofaayilii',
    password: 'Jecha Darbii',
    theme: 'Bifa',
    language: 'Afaan',
    branding: 'Mallattoo',
    profileSettings: 'Qindaa\'ina Piroofaayilii',
    fullName: 'Maqaa Guutuu',
    emailAddress: 'Teessoo Imeelii',
    saveProfile: 'Piroofaayilii Olkaa\'i',
    changePassword: 'Jecha Darbii Jijjiiri',
    currentPassword: 'Jecha Darbii Ammaa',
    newPassword: 'Jecha Darbii Haaraa',
    confirmPassword: 'Jecha Darbii Haaraa Mirkaneessi',
    themeSettings: 'Qindaa\'ina Bifaa',
    darkMode: 'Haala Dukkanaa',
    colorPresets: 'Halluu Dursanii Qophaa\'an',
    customColors: 'Halluu Filannoo',
    primaryColor: 'Halluu Jalqabaa',
    secondaryColor: 'Halluu Lammaffaa',
    preview: 'Durargii',
    saveTheme: 'Bifa Olkaa\'i',
    languageSettings: 'Qindaa\'ina Afaanii',
    brandingSettings: 'Qindaa\'ina Mallattoo',
    websiteIcon: 'Mallattoo Marsariitii',
    uploadIcon: 'Mallattoo Olkaa\'i',
    // List Pages
    studentDirectory: 'Galmee Barattootaa',
    studentDirectoryDesc: 'Barattoota fi sanadoota isaanii bulchi',
    staffDirectory: 'Galmee Hojjettootaa',
    staffDirectoryDesc: 'Hojjettoota fi sanadoota isaanii bulchi',
    searchByName: 'Maqaan barbaadi...',
    searchStudents: 'Maqaa, eegduu, bilbilaan barbaadi...',
    searchStaff: 'Maqaa, imeelii, bilbilaan barbaadi...',
    allGenders: 'Saala Hunda',
    male: 'Dhiira',
    female: 'Dhalaa',
    allTypes: 'Gosa Hunda',
    totalStaff: 'Hojjettoota Waliigalaa',
    categories: 'Ramaddii',
    classes: 'Kutaalee',
    noStudentsFound: 'Barattoonni Hin Argamne',
    noStaffFound: 'Hojjettoonni Hin Argamne',
    tryAdjustingFilters: 'Barbaachaa ykn filannoo kee sirreessi',
    documents: 'Sanadoota',
    document: 'Sanadaa',
    basicInformation: 'Odeeffannoo Bu\'uuraa',
    loginCredentials: 'Ragaa Seensaa',
    studentAccount: 'Herrega Barataa',
    guardianAccount: 'Herrega Eegduu',
    username: 'Maqaa Fayyadamaa',
    documentsAndFiles: 'Sanadoota fi Faayiloota',
    download: 'Buufadhu',
    age: 'Umurii',
    guardian: 'Eegduu',
    phone: 'Bilbila',
    email: 'Imeelii',
    role: 'Gahee',
    department: 'Kutaa',
    employmentType: 'Gosa Qacarrii',
    fullTime: 'Guyyaa Guutuu',
    partTime: 'Yeroo Muraasa',
    // Schedule
    scheduleDashboard: 'Daashboordii Sagantaa',
    scheduleDesc: 'Sagantaa kutaa fi yeroo bulchi',
    timetable: 'Gabatee Yeroo',
    createSchedule: 'Sagantaa Uumi',
    viewSchedule: 'Sagantaa Ilaali',
    // Mark List
    markListView: 'Ilaalcha Tarree Qabxii',
    markListDesc: 'Qabxii barattootaa ilaali fi bulchi',
    subject: 'Barnoota',
    marks: 'Qabxii',
    grade: 'Sadarkaa',
    total: 'Waliigala',
    average: 'Giddugaleessa',
    // Evaluation
    evaluationTitle: 'Madaallii',
    evaluationDesc: 'Raawwii barattootaa madaali',
    // Attendance
    attendanceView: 'Ilaalcha Argamaa',
    attendanceDesc: 'Argama barattootaa hordofi',
    present: 'Argame',
    absent: 'Hin Argamne',
    late: 'Turte',
    // Communication
    communicationTitle: 'Quunnamtii',
    communicationDesc: 'Ergaa fi beeksisa ergi',
    sendMessage: 'Ergaa Ergi',
    announcements: 'Beeksisota',
    // Profile Pages
    posts: 'Maxxansaalee',
    evaluations: 'Madaalliiwwan',
    messages: 'Ergaalee',
    profileInformation: 'Odeeffannoo Piroofaayilii',
    accountInformation: 'Odeeffannoo Herregaa',
    back: 'Duubatti',
    fillForm: 'Unkaa Guuti',
    viewReport: 'Gabaasa Ilaali',
    inProgress: 'Hojii Irra',
    noEvaluations: 'Madaalliin hin ramadamne',
    noPosts: 'Maxxansaan hin jiru',
    noMessages: 'Ergaan hin jiru',
    // Attendance specific
    markAttendance: 'Argama Galmeessi',
    viewAttendanceMode: 'Argama Ilaali',
    permission: 'Hayyama',
    saveAttendance: 'Argama Olkaa\'i',
    createWeek: 'Torbee Uumi',
    selectWeek: 'Torbee Filadhu',
    currentWeek: 'Torbee Ammaa',
    nextWeek: 'Torbee Itti Aanee',
    // Guardian/Ward specific
    wards: 'Ijoollee',
    selectWard: 'Ijoollee Filadhu',
    wardAttendance: 'Argama Ijoollee',
    selectPeriod: 'Yeroo Filadhu',
    attendanceRecord: 'Galmee Argamaa',
    // Class/Teacher specific
    classComm: 'Kutaa',
    marklist: 'Tarree Qabxii',
    mySchedule: 'Sagantaa Koo',
    // Dark mode
    darkModeOn: 'Haalli dukkanaa banaa dha',
    darkModeOff: 'Haalli dukkanaa cufaa dha',
    settingsInfo: 'Filannoon kee ofumaan olkaa\'ama, yeroo itti aanu seentu ni yaadatama.',
    // Navigation - Additional
    evaluationBook: 'Kitaaba Madaallii',
    evalBookReports: 'Gabaasa Kitaaba Madaallii',
    evalBookAssignments: 'Ramaddii Kitaaba Madaallii',
    subAccounts: 'Herrega Gad-Aanaa',
    classTeachers: 'Barsiisota Kutaa',
    // Admin Sub-Accounts
    adminSubAccounts: 'Herrega Gad-Aanaa Bulchiinsaa',
    createSubAccount: 'Herrega Gad-Aanaa Uumi',
    editSubAccount: 'Herrega Gad-Aanaa Gulaali',
    deleteSubAccount: 'Herrega Gad-Aanaa Haqi',
    searchByNameEmailUsername: 'Maqaa, imeelii, ykn maqaa fayyadamaatiin barbaadi...',
    noSubAccountsCreated: 'Herregni gad-aanaa hin uumamne',
    noAccountsMatchSearch: 'Herregni barbaachaa kee hin argamne',
    permissions: 'Hayyamoota',
    permissionsCount: 'hayyamoota',
    status: 'Haala',
    inactive: 'Hojii Ala',
    activate: 'Hojii Irra Oolchi',
    deactivate: 'Hojii Ala Godhi',
    name: 'Maqaa',
    nameRequired: 'Maqaan barbaachisaa dha',
    emailRequired: 'Imeeliin barbaachisaa dha',
    invalidEmailFormat: 'Bifa imeelii sirrii miti',
    usernameRequired: 'Maqaan fayyadamaa barbaachisaa dha',
    passwordRequired: 'Jecha darbii barbaachisaa dha',
    passwordMinLength: 'Jecha darbii yoo xiqqaate qubee 6 qabaachuu qaba',
    leaveBlankToKeepCurrent: 'kan ammaa eeguuf duwwaa dhiisi',
    enterFullName: 'Maqaa guutuu galchi',
    enterEmailAddress: 'Teessoo imeelii galchi',
    enterUsername: 'Maqaa fayyadamaa galchi',
    enterPassword: 'Jecha darbii galchi',
    enterNewPassword: 'Jecha darbii haaraa galchi',
    accountCreatedSuccess: 'Herregni milkaa\'inaan uumame',
    accountUpdatedSuccess: 'Herregni milkaa\'inaan haaromfame',
    accountDeletedSuccess: 'Herregni milkaa\'inaan haqame',
    failedToLoadSubAccounts: 'Herrega gad-aanaa fe\'uu hin dandeenye',
    failedToSaveAccount: 'Herrega olkaa\'uu hin dandeenye',
    failedToDeleteAccount: 'Herrega haquu hin dandeenye',
    failedToToggleStatus: 'Haala jijjiiruu hin dandeenye',
    usernameAlreadyExists: 'Maqaan fayyadamaa duraan jira',
    emailAlreadyExists: 'Imeeliin duraan jira',
    confirmDeleteAccount: 'Dhuguma haquu barbaaddaa',
    actionCannotBeUndone: 'Gocha kana deebisuu hin dandaamu.',
    saving: 'Olkaa\'aa jira...',
    create: 'Uumi',
    update: 'Haaromsi',
    // Create Staff Account
    createStaffAccount: 'Herrega Hojjetaa Mana Barumsaa Uumi',
    phoneNumber: 'Lakkoofsa Bilbilaa',
    gender: 'Saala',
    selectGender: 'Saala filadhu',
    other: 'Kan biraa',
    selectRole: 'Gahee filadhu',
    teacher: 'Barsiisaa',
    admin: 'Bulchaa',
    librarian: 'Bulchaa Kitaabaa',
    principal: 'Muummee',
    counselor: 'Gorsaa',
    selectDepartment: 'Kutaa filadhu',
    science: 'Saayinsii',
    english: 'Afaan Ingilizii',
    mathematics: 'Herrega',
    history: 'Seenaa',
    it: 'IT',
    hr: 'HR',
    passwordMinLength8: 'Jecha darbii yoo xiqqaate qubee 8 qabaachuu qaba',
    passwordsDoNotMatch: 'Jecha darbii wal hin simu',
    profilePicture: 'Suuraa Piroofaayilii',
    optional: 'Dirqama miti',
    chooseFile: 'Faayilii Filadhu',
    createAccount: 'Herrega Uumi',
    reset: 'Irra Deebii',
    creating: 'Uumaa jira...',
    staffAccountCreatedSuccess: 'Herregni hojjetaa milkaa\'inaan uumame!',
    required: 'barbaachisaa',
    // Guardian Directory
    guardianDirectory: 'Galmee Eegduu',
    guardianDirectoryDesc: 'Eegdoota hunda ilaali fi bulchi',
    guardians: 'Eegdoota',
    searchGuardians: 'Eegdoota barbaadi...',
    noGuardiansFound: 'Eegduun hin argamne',
    associatedStudents: 'Barattoota Walqabatan',
    contactInformation: 'Odeeffannoo Quunnamtii',
    relation: 'Hariiroo',
    // Evaluation Book
    evaluationInbox: 'Sanduuqa Madaallii',
    evaluationInboxDesc: 'Madaallii guyyaa guyyaa ijoollee kee ilaali fi deebii kenni',
    pendingResponse: 'Deebii Eeggataa',
    responded: 'Deebii Kenname',
    noEvaluationsYet: 'Madaalliin Hin Jiru',
    noEvaluationsDesc: 'Madaalliin ilaaltu hin jiru.',
    tapToAddFeedback: 'Yaada kee dabaluuf tuqi',
    allWards: 'Ijoollee Hunda',
    // Evaluation Book Reports
    evaluationBookReports: 'Gabaasa Kitaaba Madaallii',
    evaluationBookReportsDesc: 'Gabaasa madaallii mana barumsaa guutuu ilaali',
    totalEvaluations: 'Madaallii Waliigalaa',
    pendingResponses: 'Deebii Eeggataa',
    responseRate: 'Harka Deebii',
    filters: 'Filannoo',
    startDate: 'Guyyaa Jalqabaa',
    endDate: 'Guyyaa Xumuraa',
    allClasses: 'Kutaalee Hunda',
    searchStudent: 'Barataa barbaadi...',
    clearFilters: 'Filannoo Haqi',
    noReportsFound: 'Gabaasni hin argamne',
    adjustFiltersOrWait: 'Filannoo kee sirreessi ykn madaalliin akka uumamu eegi',
    evaluationData: 'Deetaa Madaallii',
    guardianFeedback: 'Yaada Eegduu',
    submitted: 'Ergame',
    // Teacher Assignment
    teacherAssignments: 'Ramaddii Barsiisaa',
    teacherAssignmentsDesc: 'Barsiisota kutaalee sirna Kitaaba Madaalliif ramadi',
    newAssignment: 'Ramaddii Haaraa',
    selectTeacher: 'Barsiisaa filadhu...',
    selectClass: 'Kutaa filadhu...',
    assignTeacher: 'Barsiisaa Ramadi',
    assigning: 'Ramadaa jira...',
    teacherAssignedSuccess: 'Barsiisaan milkaa\'inaan ramadame',
    assignmentRemoved: 'Ramaddiin haqame',
    removeAssignment: 'Ramaddii kana haquu?',
    noAssignmentsYet: 'Ramaddiin hin jiru',
    assignTeachersAbove: 'Unka armaan olii fayyadamuun barsiisota kutaalee ramadi',
    teacherCount: 'barsiisaa(oota)',
    // Class Teacher Assignment
    classTeacherAssignment: 'Ramaddii Barsiisaa Kutaa',
    classTeacherAssignmentDesc: 'Barsiisota kutaalee bulchiinsa argamaaf ramadi',
    assignClassTeacher: 'Barsiisaa Kutaa Ramadi',
    selectTeacherLabel: 'Barsiisaa Filadhu:',
    selectClassLabel: 'Kutaa Filadhu:',
    assign: 'Ramadi',
    currentAssignments: 'Ramaddii Ammaa',
    noClassTeachersAssigned: 'Barsiisaan kutaa hin ramadamne',
    removeClassTeacher: 'Barsiisaa kutaa haqi',
    teacherUnassigned: 'Barsiisaan haqame',
    assigned: 'Ramadame',
    unassignedClasses: 'Kutaalee Hin Ramadamne',
    // Create Attendance
    createAttendance: 'Argama Uumi',
    createAttendanceDesc: 'Argama kutaa kamiifuu uumi fi bulchi',
    createNewWeek: 'Torbee Haaraa Uumi',
    editExisting: 'Kan Jiru Gulaali',
    classLabel: 'Kutaa:',
    weekStartMonday: 'Jalqaba Torbee (Wiixata):',
    selectWeekLabel: 'Torbee Filadhu:',
    selectWeekOption: '-- Torbee Filadhu --',
    createAttendanceBtn: 'Argama Uumi',
    saveAttendanceBtn: 'Argama Olkaa\'i',
    existingAttendanceWeeks: 'Torbee Argamaa Jiran',
    loadingAttendanceData: 'Deetaa argamaa fe\'aa jira...',
    noAttendanceData: 'Deetaan argamaa hin jiru',
    selectWeekToEdit: 'Argama gulaaluuf torbee filadhu',
    quickMarkAll: 'Hunda dafanii mallattessi:',
    studentName: 'Maqaa Barataa',
    presentP: 'Argame (P)',
    absentA: 'Hin Argamne (A)',
    lateL: 'Turte (L)',
    permissionE: 'Hayyama (E)',
    failedToFetchClasses: 'Kutaalee fiduu hin dandeenye',
    pleaseSelectClassAndWeek: 'Maaloo kutaa fi guyyaa jalqaba torbee filadhu',
    noAttendanceDataToSave: 'Deetaan argamaa olkaa\'amu hin jiru',
    failedToCreateAttendance: 'Argama uumuu hin dandeenye',
    failedToSaveAttendance: 'Argama olkaa\'uu hin dandeenye'
  },
  am: {
    dashboard: 'ዳሽቦርድ',
    dashboardSubtitle: 'የትምህርት ቤት አስተዳደር ስርዓት አጠቃላይ እይታ',
    registration: 'ምዝገባ',
    registerStudent: 'ተማሪ መዝግብ',
    registerStaff: 'ሰራተኛ መዝግብ',
    lists: 'ዝርዝሮች',
    students: 'ተማሪዎች',
    staff: 'ሰራተኞች',
    academic: 'ትምህርታዊ',
    evaluation: 'ግምገማ',
    markLists: 'የውጤት ዝርዝር',
    attendance: 'መገኘት',
    createMarklist: 'የውጤት ዝርዝር ፍጠር',
    reportCard: 'የሪፖርት ካርድ',
    schedule: 'መርሃ ግብር',
    post: 'ልጥፍ',
    tasks: 'የስራ ዳሽቦርድ',
    administration: 'አስተዳደር',
    communication: 'ግንኙነት',
    payments: 'ክፍያዎች',
    settings: 'ቅንብሮች',
    search: 'ፈልግ...',
    myProfile: 'የእኔ መገለጫ',
    logout: 'ውጣ',
    settingsTitle: 'ቅንብሮች',
    settingsSubtitle: 'መለያዎን እና የመተግበሪያ ምርጫዎችን ያስተዳድሩ',
    profile: 'መገለጫ',
    password: 'የይለፍ ቃል',
    theme: 'ገጽታ',
    language: 'ቋንቋ',
    branding: 'ብራንዲንግ',
    profileSettings: 'የመገለጫ ቅንብሮች',
    fullName: 'ሙሉ ስም',
    emailAddress: 'የኢሜይል አድራሻ',
    saveProfile: 'መገለጫ አስቀምጥ',
    changePassword: 'የይለፍ ቃል ቀይር',
    currentPassword: 'የአሁኑ የይለፍ ቃል',
    newPassword: 'አዲስ የይለፍ ቃል',
    confirmPassword: 'አዲስ የይለፍ ቃል አረጋግጥ',
    themeSettings: 'የገጽታ ቅንብሮች',
    darkMode: 'ጨለማ ሁነታ',
    colorPresets: 'የቀለም ቅድመ-ቅንብሮች',
    customColors: 'ብጁ ቀለሞች',
    primaryColor: 'ዋና ቀለም',
    secondaryColor: 'ሁለተኛ ቀለም',
    preview: 'ቅድመ እይታ',
    saveTheme: 'ገጽታ አስቀምጥ',
    languageSettings: 'የቋንቋ ቅንብሮች',
    brandingSettings: 'የብራንዲንግ ቅንብሮች',
    websiteIcon: 'የድረ-ገጽ አዶ',
    uploadIcon: 'አዶ ስቀል',
    save: 'አስቀምጥ',
    cancel: 'ሰርዝ',
    loading: 'በመጫን ላይ...',
    success: 'ተሳክቷል',
    error: 'ስህተት',
    delete: 'ሰርዝ',
    edit: 'አርትዕ',
    view: 'ይመልከቱ',
    refresh: 'አድስ',
    previous: 'ቀዳሚ',
    next: 'ቀጣይ',
    page: 'ገጽ',
    of: 'ከ',
    all: 'ሁሉም',
    noDataFound: 'ምንም መረጃ አልተገኘም',
    actions: 'ድርጊቶች',
    // Dashboard
    totalStudents: 'ጠቅላላ ተማሪዎች',
    attendanceRate: 'የመገኘት መጠን',
    feeCollectionRate: 'የክፍያ ስብስብ መጠን',
    vsLastMonth: 'ካለፈው ወር ጋር',
    vsYesterday: 'ከትናንት ጋር',
    attendanceTrend: 'የመገኘት አዝማሚያ',
    enrollmentTrend: 'የምዝገባ አዝማሚያ',
    financialOverview: 'የገንዘብ አጠቃላይ እይታ',
    last30Days: 'ባለፉት 30 ቀናት',
    thisAcademicYear: 'በዚህ የትምህርት ዓመት',
    currentMonth: 'የአሁኑ ወር',
    chartPlaceholder: 'የገበታ ምስላዊ እዚህ ይተገበራል',
    recentActivity: 'የቅርብ ጊዜ እንቅስቃሴ',
    latestActions: 'በስርዓቱ ውስጥ የቅርብ ጊዜ ድርጊቶች',
    upcomingEvents: 'መጪ ዝግጅቶች',
    scheduledEvents: 'የታቀዱ ፈተናዎች እና ዝግጅቶች',
    noRecentActivity: 'ምንም የቅርብ ጊዜ እንቅስቃሴ የለም',
    noUpcomingEvents: 'ምንም መጪ ዝግጅቶች የሉም',
    lastUpdated: 'መጨረሻ የዘመነው',
    minutesAgo: 'ደቂቃዎች በፊት',
    hoursAgo: 'ሰዓታት በፊት',
    daysAgo: 'ቀናት በፊት',
    // List Pages
    studentDirectory: 'የተማሪዎች ማውጫ',
    studentDirectoryDesc: 'ሁሉንም ተማሪዎች እና ሰነዶቻቸውን ያስተዳድሩ',
    staffDirectory: 'የሰራተኞች ማውጫ',
    staffDirectoryDesc: 'ሁሉንም ሰራተኞች እና ሰነዶቻቸውን ያስተዳድሩ',
    searchByName: 'በስም ፈልግ...',
    searchStudents: 'በስም፣ አሳዳጊ፣ ስልክ ፈልግ...',
    searchStaff: 'በስም፣ ኢሜይል፣ ስልክ ፈልግ...',
    allGenders: 'ሁሉም ጾታዎች',
    male: 'ወንድ',
    female: 'ሴት',
    allTypes: 'ሁሉም ዓይነቶች',
    totalStaff: 'ጠቅላላ ሰራተኞች',
    categories: 'ምድቦች',
    classes: 'ክፍሎች',
    noStudentsFound: 'ምንም ተማሪዎች አልተገኙም',
    noStaffFound: 'ምንም ሰራተኞች አልተገኙም',
    tryAdjustingFilters: 'ፍለጋዎን ወይም ማጣሪያዎችን ያስተካክሉ',
    documents: 'ሰነዶች',
    document: 'ሰነድ',
    basicInformation: 'መሰረታዊ መረጃ',
    loginCredentials: 'የመግቢያ ማረጋገጫዎች',
    studentAccount: 'የተማሪ መለያ',
    guardianAccount: 'የአሳዳጊ መለያ',
    username: 'የተጠቃሚ ስም',
    documentsAndFiles: 'ሰነዶች እና ፋይሎች',
    download: 'አውርድ',
    age: 'ዕድሜ',
    guardian: 'አሳዳጊ',
    phone: 'ስልክ',
    email: 'ኢሜይል',
    role: 'ሚና',
    department: 'ክፍል',
    employmentType: 'የቅጥር ዓይነት',
    fullTime: 'ሙሉ ጊዜ',
    partTime: 'ከፊል ጊዜ',
    // Schedule
    scheduleDashboard: 'የመርሃ ግብር ዳሽቦርድ',
    scheduleDesc: 'የክፍል መርሃ ግብሮችን ያስተዳድሩ',
    timetable: 'የጊዜ ሰሌዳ',
    createSchedule: 'መርሃ ግብር ፍጠር',
    viewSchedule: 'መርሃ ግብር ይመልከቱ',
    // Mark List
    markListView: 'የውጤት ዝርዝር እይታ',
    markListDesc: 'የተማሪዎችን ውጤት ይመልከቱ እና ያስተዳድሩ',
    subject: 'ትምህርት',
    marks: 'ውጤት',
    grade: 'ደረጃ',
    total: 'ጠቅላላ',
    average: 'አማካይ',
    // Evaluation
    evaluationTitle: 'ግምገማ',
    evaluationDesc: 'የተማሪዎችን አፈጻጸም ይገምግሙ',
    // Attendance
    attendanceView: 'የመገኘት እይታ',
    attendanceDesc: 'የተማሪዎችን መገኘት ይከታተሉ',
    present: 'ተገኝቷል',
    absent: 'አልተገኘም',
    late: 'ዘግይቷል',
    // Communication
    communicationTitle: 'ግንኙነት',
    communicationDesc: 'መልዕክቶችን እና ማስታወቂያዎችን ይላኩ',
    sendMessage: 'መልዕክት ላክ',
    announcements: 'ማስታወቂያዎች',
    // Profile Pages
    posts: 'ልጥፎች',
    evaluations: 'ግምገማዎች',
    messages: 'መልዕክቶች',
    profileInformation: 'የመገለጫ መረጃ',
    accountInformation: 'የመለያ መረጃ',
    back: 'ተመለስ',
    fillForm: 'ቅጽ ሙላ',
    viewReport: 'ሪፖርት ይመልከቱ',
    inProgress: 'በሂደት ላይ',
    noEvaluations: 'ምንም ግምገማ አልተመደበም',
    noPosts: 'ምንም ልጥፎች የሉም',
    noMessages: 'ምንም መልዕክቶች የሉም',
    // Attendance specific
    markAttendance: 'መገኘት ምልክት አድርግ',
    viewAttendanceMode: 'መገኘት ይመልከቱ',
    permission: 'ፈቃድ',
    saveAttendance: 'መገኘት አስቀምጥ',
    createWeek: 'ሳምንት ፍጠር',
    selectWeek: 'ሳምንት ይምረጡ',
    currentWeek: 'የአሁኑ ሳምንት',
    nextWeek: 'ቀጣይ ሳምንት',
    // Guardian/Ward specific
    wards: 'ልጆች',
    selectWard: 'ልጅ ይምረጡ',
    wardAttendance: 'የልጅ መገኘት',
    selectPeriod: 'ጊዜ ይምረጡ',
    attendanceRecord: 'የመገኘት መዝገብ',
    // Class/Teacher specific
    classComm: 'ክፍል',
    marklist: 'የውጤት ዝርዝር',
    mySchedule: 'የእኔ መርሃ ግብር',
    // Dark mode
    darkModeOn: 'ጨለማ ሁነታ በርቷል',
    darkModeOff: 'ጨለማ ሁነታ ጠፍቷል',
    settingsInfo: 'ምርጫዎችዎ በራስ-ሰር ይቀመጣሉ እና በሚቀጥለው ጊዜ ሲገቡ ይታወሳሉ።',
    // Navigation - Additional
    evaluationBook: 'የግምገማ መጽሐፍ',
    evalBookReports: 'የግምገማ መጽሐፍ ሪፖርቶች',
    evalBookAssignments: 'የግምገማ መጽሐፍ ምደባዎች',
    subAccounts: 'ንዑስ መለያዎች',
    classTeachers: 'የክፍል መምህራን',
    // Admin Sub-Accounts
    adminSubAccounts: 'የአስተዳዳሪ ንዑስ መለያዎች',
    createSubAccount: 'ንዑስ መለያ ፍጠር',
    editSubAccount: 'ንዑስ መለያ አርትዕ',
    deleteSubAccount: 'ንዑስ መለያ ሰርዝ',
    searchByNameEmailUsername: 'በስም፣ ኢሜይል ወይም የተጠቃሚ ስም ፈልግ...',
    noSubAccountsCreated: 'ምንም ንዑስ መለያዎች አልተፈጠሩም',
    noAccountsMatchSearch: 'ከፍለጋዎ ጋር የሚዛመድ መለያ የለም',
    permissions: 'ፈቃዶች',
    permissionsCount: 'ፈቃዶች',
    status: 'ሁኔታ',
    inactive: 'ንቁ ያልሆነ',
    activate: 'አንቃ',
    deactivate: 'አቦዝን',
    name: 'ስም',
    nameRequired: 'ስም ያስፈልጋል',
    emailRequired: 'ኢሜይል ያስፈልጋል',
    invalidEmailFormat: 'ልክ ያልሆነ የኢሜይል ቅርጸት',
    usernameRequired: 'የተጠቃሚ ስም ያስፈልጋል',
    passwordRequired: 'የይለፍ ቃል ያስፈልጋል',
    passwordMinLength: 'የይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት',
    leaveBlankToKeepCurrent: 'የአሁኑን ለማቆየት ባዶ ይተውት',
    enterFullName: 'ሙሉ ስም ያስገቡ',
    enterEmailAddress: 'የኢሜይል አድራሻ ያስገቡ',
    enterUsername: 'የተጠቃሚ ስም ያስገቡ',
    enterPassword: 'የይለፍ ቃል ያስገቡ',
    enterNewPassword: 'አዲስ የይለፍ ቃል ያስገቡ',
    accountCreatedSuccess: 'መለያ በተሳካ ሁኔታ ተፈጥሯል',
    accountUpdatedSuccess: 'መለያ በተሳካ ሁኔታ ተዘምኗል',
    accountDeletedSuccess: 'መለያ በተሳካ ሁኔታ ተሰርዟል',
    failedToLoadSubAccounts: 'ንዑስ መለያዎችን መጫን አልተሳካም',
    failedToSaveAccount: 'መለያ ማስቀመጥ አልተሳካም',
    failedToDeleteAccount: 'መለያ መሰረዝ አልተሳካም',
    failedToToggleStatus: 'ሁኔታ መቀየር አልተሳካም',
    usernameAlreadyExists: 'የተጠቃሚ ስም አስቀድሞ አለ',
    emailAlreadyExists: 'ኢሜይል አስቀድሞ አለ',
    confirmDeleteAccount: 'እርግጠኛ ነዎት መሰረዝ ይፈልጋሉ',
    actionCannotBeUndone: 'ይህ ድርጊት መቀልበስ አይቻልም።',
    saving: 'በማስቀመጥ ላይ...',
    create: 'ፍጠር',
    update: 'አዘምን',
    // Create Staff Account
    createStaffAccount: 'የትምህርት ቤት ሰራተኛ መለያ ፍጠር',
    phoneNumber: 'ስልክ ቁጥር',
    gender: 'ጾታ',
    selectGender: 'ጾታ ይምረጡ',
    other: 'ሌላ',
    selectRole: 'ሚና ይምረጡ',
    teacher: 'መምህር',
    admin: 'አስተዳዳሪ',
    librarian: 'ቤተ-መጻሕፍት ሰራተኛ',
    principal: 'ርዕሰ መምህር',
    counselor: 'አማካሪ',
    selectDepartment: 'ክፍል ይምረጡ',
    science: 'ሳይንስ',
    english: 'እንግሊዝኛ',
    mathematics: 'ሂሳብ',
    history: 'ታሪክ',
    it: 'IT',
    hr: 'HR',
    passwordMinLength8: 'የይለፍ ቃል ቢያንስ 8 ቁምፊዎች መሆን አለበት',
    passwordsDoNotMatch: 'የይለፍ ቃሎች አይዛመዱም',
    profilePicture: 'የመገለጫ ፎቶ',
    optional: 'አማራጭ',
    chooseFile: 'ፋይል ይምረጡ',
    createAccount: 'መለያ ፍጠር',
    reset: 'ዳግም አስጀምር',
    creating: 'በመፍጠር ላይ...',
    staffAccountCreatedSuccess: 'የሰራተኛ መለያ በተሳካ ሁኔታ ተፈጥሯል!',
    required: 'ያስፈልጋል',
    // Guardian Directory
    guardianDirectory: 'የአሳዳጊዎች ማውጫ',
    guardianDirectoryDesc: 'ሁሉንም አሳዳጊዎች ይመልከቱ እና ያስተዳድሩ',
    guardians: 'አሳዳጊዎች',
    searchGuardians: 'አሳዳጊዎችን ፈልግ...',
    noGuardiansFound: 'ምንም አሳዳጊዎች አልተገኙም',
    associatedStudents: 'ተያያዥ ተማሪዎች',
    contactInformation: 'የመገናኛ መረጃ',
    relation: 'ግንኙነት',
    // Evaluation Book
    evaluationInbox: 'የግምገማ ገቢ ሳጥን',
    evaluationInboxDesc: 'የልጅዎን ዕለታዊ ግምገማዎች ይመልከቱ እና ምላሽ ይስጡ',
    pendingResponse: 'ምላሽ በመጠባበቅ ላይ',
    responded: 'ምላሽ ተሰጥቷል',
    noEvaluationsYet: 'ምንም ግምገማዎች የሉም',
    noEvaluationsDesc: 'ለመመልከት ምንም ግምገማዎች የሉዎትም።',
    tapToAddFeedback: 'አስተያየትዎን ለመጨመር ይንኩ',
    allWards: 'ሁሉም ልጆች',
    // Evaluation Book Reports
    evaluationBookReports: 'የግምገማ መጽሐፍ ሪፖርቶች',
    evaluationBookReportsDesc: 'በትምህርት ቤቱ ውስጥ ያሉ ሁሉንም የግምገማ ሪፖርቶች ይመልከቱ',
    totalEvaluations: 'ጠቅላላ ግምገማዎች',
    pendingResponses: 'በመጠባበቅ ላይ ያሉ ምላሾች',
    responseRate: 'የምላሽ መጠን',
    filters: 'ማጣሪያዎች',
    startDate: 'የመጀመሪያ ቀን',
    endDate: 'የመጨረሻ ቀን',
    allClasses: 'ሁሉም ክፍሎች',
    searchStudent: 'ተማሪ ፈልግ...',
    clearFilters: 'ማጣሪያዎችን አጽዳ',
    noReportsFound: 'ምንም ሪፖርቶች አልተገኙም',
    adjustFiltersOrWait: 'ማጣሪያዎችዎን ያስተካክሉ ወይም ግምገማዎች እስኪፈጠሩ ይጠብቁ',
    evaluationData: 'የግምገማ መረጃ',
    guardianFeedback: 'የአሳዳጊ አስተያየት',
    submitted: 'ቀርቧል',
    // Teacher Assignment
    teacherAssignments: 'የመምህር ምደባዎች',
    teacherAssignmentsDesc: 'ለግምገማ መጽሐፍ ስርዓት መምህራንን ለክፍሎች ይመድቡ',
    newAssignment: 'አዲስ ምደባ',
    selectTeacher: 'መምህር ይምረጡ...',
    selectClass: 'ክፍል ይምረጡ...',
    assignTeacher: 'መምህር ይመድቡ',
    assigning: 'በመመደብ ላይ...',
    teacherAssignedSuccess: 'መምህር በተሳካ ሁኔታ ተመድቧል',
    assignmentRemoved: 'ምደባ ተወግዷል',
    removeAssignment: 'ይህን ምደባ ያስወግዱ?',
    noAssignmentsYet: 'ገና ምንም ምደባዎች የሉም',
    assignTeachersAbove: 'ከላይ ያለውን ቅጽ በመጠቀም መምህራንን ለክፍሎች ይመድቡ',
    teacherCount: 'መምህር(ራን)',
    // Class Teacher Assignment
    classTeacherAssignment: 'የክፍል መምህር ምደባ',
    classTeacherAssignmentDesc: 'ለመገኘት አስተዳደር መምህራንን ለክፍሎች ይመድቡ',
    assignClassTeacher: 'የክፍል መምህር ይመድቡ',
    selectTeacherLabel: 'መምህር ይምረጡ:',
    selectClassLabel: 'ክፍል ይምረጡ:',
    assign: 'ይመድቡ',
    currentAssignments: 'የአሁኑ ምደባዎች',
    noClassTeachersAssigned: 'ገና ምንም የክፍል መምህራን አልተመደቡም',
    removeClassTeacher: 'የክፍል መምህር ያስወግዱ ከ',
    teacherUnassigned: 'መምህር ተወግዷል ከ',
    assigned: 'ተመድቧል',
    unassignedClasses: 'ያልተመደቡ ክፍሎች',
    // Create Attendance
    createAttendance: 'መገኘት ፍጠር',
    createAttendanceDesc: 'ለማንኛውም ክፍል መገኘት ፍጠር እና ያስተዳድሩ',
    createNewWeek: 'አዲስ ሳምንት ፍጠር',
    editExisting: 'ያለውን አርትዕ',
    classLabel: 'ክፍል:',
    weekStartMonday: 'የሳምንት መጀመሪያ (ሰኞ):',
    selectWeekLabel: 'ሳምንት ይምረጡ:',
    selectWeekOption: '-- ሳምንት ይምረጡ --',
    createAttendanceBtn: 'መገኘት ፍጠር',
    saveAttendanceBtn: 'መገኘት አስቀምጥ',
    existingAttendanceWeeks: 'ያሉ የመገኘት ሳምንቶች ለ',
    loadingAttendanceData: 'የመገኘት መረጃ በመጫን ላይ...',
    noAttendanceData: 'ምንም የመገኘት መረጃ የለም',
    selectWeekToEdit: 'መገኘትን ለማርትዕ ሳምንት ይምረጡ',
    quickMarkAll: 'ሁሉንም በፍጥነት ምልክት አድርግ:',
    studentName: 'የተማሪ ስም',
    presentP: 'ተገኝቷል (P)',
    absentA: 'አልተገኘም (A)',
    lateL: 'ዘግይቷል (L)',
    permissionE: 'ፈቃድ (E)',
    failedToFetchClasses: 'ክፍሎችን ማምጣት አልተሳካም',
    pleaseSelectClassAndWeek: 'እባክዎ ክፍል እና የሳምንት መጀመሪያ ቀን ይምረጡ',
    noAttendanceDataToSave: 'የሚቀመጥ የመገኘት መረጃ የለም',
    failedToCreateAttendance: 'መገኘት መፍጠር አልተሳካም',
    failedToSaveAttendance: 'መገኘት ማስቀመጥ አልተሳካም'
  },
  so: {
    dashboard: 'Dashboorkii',
    registration: 'Diiwaangelinta',
    registerStudent: 'Arday Diiwaan Geli',
    registerStaff: 'Shaqaale Diiwaan Geli',
    lists: 'Liisaska',
    students: 'Ardayda',
    staff: 'Shaqaalaha',
    academic: 'Waxbarasho',
    evaluation: 'Qiimaynta',
    markLists: 'Liiska Dhibcaha',
    attendance: 'Imaanshaha',
    createMarklist: 'Samee Liiska Dhibcaha',
    reportCard: 'Kaarka Warbixinta',
    schedule: 'Jadwalka',
    post: 'Qoraalka',
    tasks: 'Dashboorkii Hawlaha',
    administration: 'Maamulka',
    communication: 'Isgaarsiinta',
    payments: 'Lacag Bixinta',
    settings: 'Dejinta',
    search: 'Raadi...',
    myProfile: 'Astaamahayga',
    logout: 'Ka Bax',
    settingsTitle: 'Dejinta',
    settingsSubtitle: 'Maamul akoonkaaga iyo doorashooyinka app-ka',
    profile: 'Astaan',
    password: 'Furaha Sirta',
    theme: 'Muuqaalka',
    language: 'Luuqadda',
    branding: 'Sumadda',
    profileSettings: 'Dejinta Astaanta',
    fullName: 'Magaca Buuxa',
    emailAddress: 'Cinwaanka Iimaylka',
    saveProfile: 'Kaydi Astaanta',
    changePassword: 'Beddel Furaha Sirta',
    currentPassword: 'Furaha Sirta Hadda',
    newPassword: 'Furaha Sirta Cusub',
    confirmPassword: 'Xaqiiji Furaha Sirta Cusub',
    themeSettings: 'Dejinta Muuqaalka',
    darkMode: 'Habka Mugdiga',
    colorPresets: 'Midabada Diyaarsan',
    customColors: 'Midabada Gaarka ah',
    primaryColor: 'Midabka Koowaad',
    secondaryColor: 'Midabka Labaad',
    preview: 'Horfiirin',
    saveTheme: 'Kaydi Muuqaalka',
    languageSettings: 'Dejinta Luuqadda',
    brandingSettings: 'Dejinta Sumadda',
    websiteIcon: 'Astaamaha Websaydhka',
    uploadIcon: 'Soo Geli Astaanta',
    save: 'Kaydi',
    cancel: 'Jooji',
    loading: 'Waa la soo rarayaa...',
    success: 'Guul',
    error: 'Khalad',
    delete: 'Tirtir',
    edit: 'Wax ka beddel',
    view: 'Fiiri',
    refresh: 'Cusboonaysii',
    previous: 'Hore',
    next: 'Xiga',
    page: 'Bog',
    of: 'ka mid ah',
    all: 'Dhammaan',
    noDataFound: 'Xog lama helin',
    actions: 'Ficilada',
    // List Pages
    studentDirectory: 'Buugga Ardayda',
    studentDirectoryDesc: 'Maamul dhammaan ardayda iyo dukumeentiyada',
    staffDirectory: 'Buugga Shaqaalaha',
    staffDirectoryDesc: 'Maamul dhammaan shaqaalaha iyo dukumeentiyada',
    searchByName: 'Ku raadi magaca...',
    searchStudents: 'Ku raadi magaca, masuulka, telefoonka...',
    searchStaff: 'Ku raadi magaca, iimaylka, telefoonka...',
    allGenders: 'Dhammaan Jinsiyada',
    male: 'Lab',
    female: 'Dheddig',
    allTypes: 'Dhammaan Noocyada',
    totalStaff: 'Wadarta Shaqaalaha',
    categories: 'Qaybaha',
    classes: 'Fasalada',
    noStudentsFound: 'Arday lama helin',
    noStaffFound: 'Shaqaale lama helin',
    tryAdjustingFilters: 'Isku day inaad hagaajiso raadintaada',
    documents: 'Dukumeentiyada',
    document: 'Dukumeenti',
    basicInformation: 'Macluumaadka Aasaasiga',
    loginCredentials: 'Aqoonsiga Gelitaanka',
    studentAccount: 'Akoonka Ardayga',
    guardianAccount: 'Akoonka Masuulka',
    username: 'Magaca Isticmaalaha',
    documentsAndFiles: 'Dukumeentiyada iyo Faylasha',
    download: 'Soo Degso',
    age: 'Da\'da',
    guardian: 'Masuulka',
    phone: 'Telefoon',
    email: 'Iimayl',
    role: 'Doorka',
    department: 'Waaxda',
    employmentType: 'Nooca Shaqada',
    fullTime: 'Waqti Buuxa',
    partTime: 'Waqti Gaaban',
    // Schedule
    scheduleDashboard: 'Dashboorkii Jadwalka',
    scheduleDesc: 'Maamul jadwalka fasalada',
    timetable: 'Jadwalka Waqtiga',
    createSchedule: 'Samee Jadwal',
    viewSchedule: 'Fiiri Jadwalka',
    // Mark List
    markListView: 'Aragtida Liiska Dhibcaha',
    markListDesc: 'Fiiri oo maamul dhibcaha ardayda',
    subject: 'Maadada',
    marks: 'Dhibcaha',
    grade: 'Darajada',
    total: 'Wadarta',
    average: 'Celceliska',
    // Evaluation
    evaluationTitle: 'Qiimaynta',
    evaluationDesc: 'Qiimee waxqabadka ardayda',
    // Attendance
    attendanceView: 'Aragtida Imaanshaha',
    attendanceDesc: 'La soco imaanshaha ardayda',
    present: 'Jooga',
    absent: 'Maqan',
    late: 'Dib u dhacay',
    // Communication
    communicationTitle: 'Isgaarsiinta',
    communicationDesc: 'Dir fariimaha iyo ogeysiisyada',
    sendMessage: 'Dir Fariin',
    announcements: 'Ogeysiisyada',
    // Profile Pages
    posts: 'Qoraallada',
    evaluations: 'Qiimaynta',
    messages: 'Fariimaha',
    profileInformation: 'Macluumaadka Astaanta',
    accountInformation: 'Macluumaadka Akoonka',
    back: 'Dib u noqo',
    fillForm: 'Buuxi Foomka',
    viewReport: 'Fiiri Warbixinta',
    inProgress: 'Socda',
    noEvaluations: 'Qiimayn lama qoondeyn',
    noPosts: 'Qoraal ma jiro',
    noMessages: 'Fariin ma jiro',
    // Attendance specific
    markAttendance: 'Calaamadee Imaanshaha',
    viewAttendanceMode: 'Fiiri Imaanshaha',
    permission: 'Fasax',
    saveAttendance: 'Kaydi Imaanshaha',
    createWeek: 'Samee Toddobaad',
    selectWeek: 'Dooro Toddobaad',
    currentWeek: 'Toddobaadkan',
    nextWeek: 'Toddobaadka Xiga',
    // Guardian/Ward specific
    wards: 'Carruurta',
    selectWard: 'Dooro Ilmo',
    wardAttendance: 'Imaanshaha Ilmaha',
    selectPeriod: 'Dooro Waqtiga',
    attendanceRecord: 'Diiwaanka Imaanshaha',
    // Class/Teacher specific
    classComm: 'Fasalka',
    marklist: 'Liiska Dhibcaha',
    mySchedule: 'Jadwalkayga',
    // Dark mode
    darkModeOn: 'Habka mugdiga waa shidan yahay',
    darkModeOff: 'Habka mugdiga waa daman yahay',
    settingsInfo: 'Doorashooyinkaaga si toos ah ayaa loo kaydiyaa waxaana la xasuusan doonaa markii xigta ee aad soo gasho.',
    // Navigation - Additional
    evaluationBook: 'Buugga Qiimaynta',
    evalBookReports: 'Warbixinta Buugga Qiimaynta',
    evalBookAssignments: 'Qoondeynta Buugga Qiimaynta',
    subAccounts: 'Akoonada Hoose',
    classTeachers: 'Macallimiinta Fasalka',
    // Guardian Directory
    guardianDirectory: 'Buugga Masuulka',
    guardianDirectoryDesc: 'Fiiri oo maamul dhammaan masuulka',
    guardians: 'Masuulka',
    searchGuardians: 'Raadi masuulka...',
    noGuardiansFound: 'Masuul lama helin',
    associatedStudents: 'Ardayda La Xiriira',
    contactInformation: 'Macluumaadka Xiriirka',
    relation: 'Xiriirka',
    // Evaluation Book
    evaluationInbox: 'Sanduuqa Qiimaynta',
    evaluationInboxDesc: 'Fiiri oo ka jawaab qiimaynta maalinlaha ah ee ilmahaaga',
    pendingResponse: 'Jawaab La Sugayo',
    responded: 'La Jawaabay',
    noEvaluationsYet: 'Qiimayn Ma Jirto',
    noEvaluationsDesc: 'Qiimayn aad fiiriso ma jirto.',
    tapToAddFeedback: 'Taabo si aad u darto ra\'yigaaga',
    allWards: 'Dhammaan Carruurta',
    // Evaluation Book Reports
    evaluationBookReports: 'Warbixinta Buugga Qiimaynta',
    evaluationBookReportsDesc: 'Fiiri dhammaan warbixinta qiimaynta iskuulka oo dhan',
    totalEvaluations: 'Wadarta Qiimaynta',
    pendingResponses: 'Jawaabaha La Sugayo',
    responseRate: 'Heerka Jawaabta',
    filters: 'Shaandhaynnada',
    startDate: 'Taariikhda Bilowga',
    endDate: 'Taariikhda Dhammaadka',
    allClasses: 'Dhammaan Fasalada',
    searchStudent: 'Raadi arday...',
    clearFilters: 'Nadiifi Shaandhaynnada',
    noReportsFound: 'Warbixin lama helin',
    adjustFiltersOrWait: 'Hagaaji shaandhaynadaada ama sug qiimaynta in la sameeyo',
    evaluationData: 'Xogta Qiimaynta',
    guardianFeedback: 'Ra\'yiga Masuulka',
    submitted: 'La Gudbiyay',
    // Teacher Assignment
    teacherAssignments: 'Qoondeynta Macalinka',
    teacherAssignmentsDesc: 'U qoondee macallimiinta fasalada nidaamka Buugga Qiimaynta',
    newAssignment: 'Qoondeyn Cusub',
    selectTeacher: 'Dooro macalin...',
    selectClass: 'Dooro fasal...',
    assignTeacher: 'Qoondee Macalin',
    assigning: 'Qoondeynaya...',
    teacherAssignedSuccess: 'Macalinka si guul leh ayaa loo qoondeeyay',
    assignmentRemoved: 'Qoondeynta waa la tirtiray',
    removeAssignment: 'Tirtir qoondeyntan?',
    noAssignmentsYet: 'Weli qoondeyn ma jirto',
    assignTeachersAbove: 'Isticmaal foomka sare si aad macallimiinta ugu qoondeeyso fasalada',
    teacherCount: 'macalin(imiinta)',
    // Class Teacher Assignment
    classTeacherAssignment: 'Qoondeynta Macalinka Fasalka',
    classTeacherAssignmentDesc: 'U qoondee macallimiinta fasalada maamulka imaanshaha',
    assignClassTeacher: 'Qoondee Macalinka Fasalka',
    selectTeacherLabel: 'Dooro Macalin:',
    selectClassLabel: 'Dooro Fasal:',
    assign: 'Qoondee',
    currentAssignments: 'Qoondeynta Hadda',
    noClassTeachersAssigned: 'Weli macalin fasal lama qoondeyn',
    removeClassTeacher: 'Ka saar macalinka fasalka',
    teacherUnassigned: 'Macalinka waa laga saaray',
    assigned: 'La Qoondeeyay',
    unassignedClasses: 'Fasalada Aan La Qoondeyn',
    // Create Attendance
    createAttendance: 'Samee Imaansho',
    createAttendanceDesc: 'Samee oo maamul imaanshaha fasal kasta',
    createNewWeek: 'Samee Toddobaad Cusub',
    editExisting: 'Wax Ka Beddel Kan Jira',
    classLabel: 'Fasal:',
    weekStartMonday: 'Bilowga Toddobaadka (Isniin):',
    selectWeekLabel: 'Dooro Toddobaad:',
    selectWeekOption: '-- Dooro Toddobaad --',
    createAttendanceBtn: 'Samee Imaansho',
    saveAttendanceBtn: 'Kaydi Imaanshaha',
    existingAttendanceWeeks: 'Toddobaadyada Imaanshaha ee Jira',
    loadingAttendanceData: 'Xogta imaanshaha waa la soo rarayaa...',
    noAttendanceData: 'Xog imaansho ma jirto',
    selectWeekToEdit: 'Dooro toddobaad si aad u wax ka beddesho imaanshaha',
    quickMarkAll: 'Dhammaan si dhakhso ah u calaamadee:',
    studentName: 'Magaca Ardayga',
    presentP: 'Jooga (P)',
    absentA: 'Maqan (A)',
    lateL: 'Dib u dhacay (L)',
    permissionE: 'Fasax (E)',
    failedToFetchClasses: 'Fasalada soo dejinta ma guulaysan',
    pleaseSelectClassAndWeek: 'Fadlan dooro fasal iyo taariikhda bilowga toddobaadka',
    noAttendanceDataToSave: 'Xog imaansho oo la kaydiyo ma jirto',
    failedToCreateAttendance: 'Imaanshaha samaynta ma guulaysan',
    failedToSaveAttendance: 'Imaanshaha kaydinta ma guulaysan'
  },
  ar: {
    dashboard: 'لوحة التحكم',
    dashboardSubtitle: 'نظرة عامة على نظام إدارة المدرسة',
    registration: 'التسجيل',
    registerStudent: 'تسجيل طالب',
    registerStaff: 'تسجيل موظف',
    lists: 'القوائم',
    students: 'الطلاب',
    staff: 'الموظفون',
    academic: 'أكاديمي',
    evaluation: 'التقييم',
    markLists: 'قوائم الدرجات',
    attendance: 'الحضور',
    createMarklist: 'إنشاء قائمة درجات',
    reportCard: 'بطاقة التقرير',
    schedule: 'الجدول',
    post: 'منشور',
    tasks: 'لوحة المهام',
    administration: 'الإدارة',
    communication: 'التواصل',
    payments: 'المدفوعات',
    settings: 'الإعدادات',
    search: 'بحث...',
    myProfile: 'ملفي الشخصي',
    logout: 'تسجيل الخروج',
    settingsTitle: 'الإعدادات',
    settingsSubtitle: 'إدارة حسابك وتفضيلات التطبيق',
    profile: 'الملف الشخصي',
    password: 'كلمة المرور',
    theme: 'المظهر',
    language: 'اللغة',
    branding: 'العلامة التجارية',
    profileSettings: 'إعدادات الملف الشخصي',
    fullName: 'الاسم الكامل',
    emailAddress: 'عنوان البريد الإلكتروني',
    saveProfile: 'حفظ الملف الشخصي',
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    themeSettings: 'إعدادات المظهر',
    darkMode: 'الوضع الداكن',
    colorPresets: 'ألوان مسبقة',
    customColors: 'ألوان مخصصة',
    primaryColor: 'اللون الأساسي',
    secondaryColor: 'اللون الثانوي',
    preview: 'معاينة',
    saveTheme: 'حفظ المظهر',
    languageSettings: 'إعدادات اللغة',
    brandingSettings: 'إعدادات العلامة التجارية',
    websiteIcon: 'أيقونة الموقع',
    uploadIcon: 'رفع الأيقونة',
    save: 'حفظ',
    cancel: 'إلغاء',
    loading: 'جاري التحميل...',
    success: 'نجاح',
    error: 'خطأ',
    delete: 'حذف',
    edit: 'تعديل',
    view: 'عرض',
    refresh: 'تحديث',
    previous: 'السابق',
    next: 'التالي',
    page: 'صفحة',
    of: 'من',
    all: 'الكل',
    noDataFound: 'لم يتم العثور على بيانات',
    actions: 'الإجراءات',
    // Dashboard
    totalStudents: 'إجمالي الطلاب',
    attendanceRate: 'معدل الحضور',
    feeCollectionRate: 'معدل تحصيل الرسوم',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    vsYesterday: 'مقارنة بالأمس',
    attendanceTrend: 'اتجاه الحضور',
    enrollmentTrend: 'اتجاه التسجيل',
    financialOverview: 'نظرة عامة مالية',
    last30Days: 'آخر 30 يومًا',
    thisAcademicYear: 'هذا العام الدراسي',
    currentMonth: 'الشهر الحالي',
    chartPlaceholder: 'سيتم تنفيذ تصور الرسم البياني هنا',
    recentActivity: 'النشاط الأخير',
    latestActions: 'أحدث الإجراءات في النظام',
    upcomingEvents: 'الأحداث القادمة',
    scheduledEvents: 'الامتحانات والأحداث المجدولة',
    noRecentActivity: 'لا يوجد نشاط حديث',
    noUpcomingEvents: 'لا توجد أحداث قادمة',
    lastUpdated: 'آخر تحديث',
    minutesAgo: 'دقائق مضت',
    hoursAgo: 'ساعات مضت',
    daysAgo: 'أيام مضت',
    // List Pages
    studentDirectory: 'دليل الطلاب',
    studentDirectoryDesc: 'إدارة جميع الطلاب ووثائقهم',
    staffDirectory: 'دليل الموظفين',
    staffDirectoryDesc: 'إدارة جميع الموظفين ووثائقهم',
    searchByName: 'البحث بالاسم...',
    searchStudents: 'البحث بالاسم، ولي الأمر، الهاتف...',
    searchStaff: 'البحث بالاسم، البريد الإلكتروني، الهاتف...',
    allGenders: 'جميع الأجناس',
    male: 'ذكر',
    female: 'أنثى',
    allTypes: 'جميع الأنواع',
    totalStaff: 'إجمالي الموظفين',
    categories: 'الفئات',
    classes: 'الفصول',
    noStudentsFound: 'لم يتم العثور على طلاب',
    noStaffFound: 'لم يتم العثور على موظفين',
    tryAdjustingFilters: 'حاول تعديل البحث أو الفلاتر',
    documents: 'المستندات',
    document: 'مستند',
    basicInformation: 'المعلومات الأساسية',
    loginCredentials: 'بيانات تسجيل الدخول',
    studentAccount: 'حساب الطالب',
    guardianAccount: 'حساب ولي الأمر',
    username: 'اسم المستخدم',
    documentsAndFiles: 'المستندات والملفات',
    download: 'تحميل',
    age: 'العمر',
    guardian: 'ولي الأمر',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    role: 'الدور',
    department: 'القسم',
    employmentType: 'نوع التوظيف',
    fullTime: 'دوام كامل',
    partTime: 'دوام جزئي',
    // Schedule
    scheduleDashboard: 'لوحة الجدول',
    scheduleDesc: 'إدارة جداول الفصول',
    timetable: 'الجدول الزمني',
    createSchedule: 'إنشاء جدول',
    viewSchedule: 'عرض الجدول',
    // Mark List
    markListView: 'عرض قائمة الدرجات',
    markListDesc: 'عرض وإدارة درجات الطلاب',
    subject: 'المادة',
    marks: 'الدرجات',
    grade: 'التقدير',
    total: 'المجموع',
    average: 'المتوسط',
    // Evaluation
    evaluationTitle: 'التقييم',
    evaluationDesc: 'تقييم أداء الطلاب',
    // Attendance
    attendanceView: 'عرض الحضور',
    attendanceDesc: 'تتبع حضور الطلاب',
    present: 'حاضر',
    absent: 'غائب',
    late: 'متأخر',
    // Communication
    communicationTitle: 'التواصل',
    communicationDesc: 'إرسال الرسائل والإعلانات',
    sendMessage: 'إرسال رسالة',
    announcements: 'الإعلانات',
    // Profile Pages
    posts: 'المنشورات',
    evaluations: 'التقييمات',
    messages: 'الرسائل',
    profileInformation: 'معلومات الملف الشخصي',
    accountInformation: 'معلومات الحساب',
    back: 'رجوع',
    fillForm: 'ملء النموذج',
    viewReport: 'عرض التقرير',
    inProgress: 'قيد التنفيذ',
    noEvaluations: 'لا توجد تقييمات مخصصة',
    noPosts: 'لا توجد منشورات',
    noMessages: 'لا توجد رسائل',
    // Attendance specific
    markAttendance: 'تسجيل الحضور',
    viewAttendanceMode: 'عرض الحضور',
    permission: 'إذن',
    saveAttendance: 'حفظ الحضور',
    createWeek: 'إنشاء أسبوع',
    selectWeek: 'اختر الأسبوع',
    currentWeek: 'الأسبوع الحالي',
    nextWeek: 'الأسبوع القادم',
    // Guardian/Ward specific
    wards: 'الأبناء',
    selectWard: 'اختر الابن',
    wardAttendance: 'حضور الابن',
    selectPeriod: 'اختر الفترة',
    attendanceRecord: 'سجل الحضور',
    // Class/Teacher specific
    classComm: 'الفصل',
    marklist: 'قائمة الدرجات',
    mySchedule: 'جدولي',
    // Dark mode
    darkModeOn: 'الوضع الداكن مفعل',
    darkModeOff: 'الوضع الداكن معطل',
    settingsInfo: 'يتم حفظ تفضيلاتك تلقائياً وسيتم تذكرها في المرة القادمة التي تسجل فيها الدخول.',
    // Navigation - Additional
    evaluationBook: 'دفتر التقييم',
    evalBookReports: 'تقارير دفتر التقييم',
    evalBookAssignments: 'تعيينات دفتر التقييم',
    subAccounts: 'الحسابات الفرعية',
    classTeachers: 'معلمو الفصول',
    // Guardian Directory
    guardianDirectory: 'دليل أولياء الأمور',
    guardianDirectoryDesc: 'عرض وإدارة جميع أولياء الأمور',
    guardians: 'أولياء الأمور',
    searchGuardians: 'البحث عن أولياء الأمور...',
    noGuardiansFound: 'لم يتم العثور على أولياء أمور',
    associatedStudents: 'الطلاب المرتبطون',
    contactInformation: 'معلومات الاتصال',
    relation: 'العلاقة',
    // Evaluation Book
    evaluationInbox: 'صندوق التقييم',
    evaluationInboxDesc: 'راجع وأجب على تقييمات طفلك اليومية',
    pendingResponse: 'في انتظار الرد',
    responded: 'تم الرد',
    noEvaluationsYet: 'لا توجد تقييمات',
    noEvaluationsDesc: 'ليس لديك أي تقييمات للمراجعة حتى الآن.',
    tapToAddFeedback: 'انقر لإضافة ملاحظاتك',
    allWards: 'جميع الأبناء',
    // Evaluation Book Reports
    evaluationBookReports: 'تقارير دفتر التقييم',
    evaluationBookReportsDesc: 'عرض جميع تقارير التقييم في المدرسة',
    totalEvaluations: 'إجمالي التقييمات',
    pendingResponses: 'الردود المعلقة',
    responseRate: 'معدل الاستجابة',
    filters: 'الفلاتر',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    allClasses: 'جميع الفصول',
    searchStudent: 'البحث عن طالب...',
    clearFilters: 'مسح الفلاتر',
    noReportsFound: 'لم يتم العثور على تقارير',
    adjustFiltersOrWait: 'عدّل الفلاتر أو انتظر إنشاء التقييمات',
    evaluationData: 'بيانات التقييم',
    guardianFeedback: 'ملاحظات ولي الأمر',
    submitted: 'تم الإرسال',
    // Teacher Assignment
    teacherAssignments: 'تعيينات المعلمين',
    teacherAssignmentsDesc: 'تعيين المعلمين للفصول لنظام دفتر التقييم',
    newAssignment: 'تعيين جديد',
    selectTeacher: 'اختر معلماً...',
    selectClass: 'اختر فصلاً...',
    assignTeacher: 'تعيين المعلم',
    assigning: 'جاري التعيين...',
    teacherAssignedSuccess: 'تم تعيين المعلم بنجاح',
    assignmentRemoved: 'تم إزالة التعيين',
    removeAssignment: 'إزالة هذا التعيين؟',
    noAssignmentsYet: 'لا توجد تعيينات بعد',
    assignTeachersAbove: 'عيّن المعلمين للفصول باستخدام النموذج أعلاه',
    teacherCount: 'معلم(ين)',
    // Class Teacher Assignment
    classTeacherAssignment: 'تعيين معلم الفصل',
    classTeacherAssignmentDesc: 'تعيين المعلمين للفصول لإدارة الحضور',
    assignClassTeacher: 'تعيين معلم الفصل',
    selectTeacherLabel: 'اختر المعلم:',
    selectClassLabel: 'اختر الفصل:',
    assign: 'تعيين',
    currentAssignments: 'التعيينات الحالية',
    noClassTeachersAssigned: 'لم يتم تعيين معلمي فصول بعد',
    removeClassTeacher: 'إزالة معلم الفصل من',
    teacherUnassigned: 'تم إلغاء تعيين المعلم من',
    assigned: 'تم التعيين',
    unassignedClasses: 'الفصول غير المعينة',
    // Create Attendance
    createAttendance: 'إنشاء الحضور',
    createAttendanceDesc: 'إنشاء وإدارة الحضور لأي فصل',
    createNewWeek: 'إنشاء أسبوع جديد',
    editExisting: 'تعديل الموجود',
    classLabel: 'الفصل:',
    weekStartMonday: 'بداية الأسبوع (الاثنين):',
    selectWeekLabel: 'اختر الأسبوع:',
    selectWeekOption: '-- اختر الأسبوع --',
    createAttendanceBtn: 'إنشاء الحضور',
    saveAttendanceBtn: 'حفظ الحضور',
    existingAttendanceWeeks: 'أسابيع الحضور الموجودة لـ',
    loadingAttendanceData: 'جاري تحميل بيانات الحضور...',
    noAttendanceData: 'لا توجد بيانات حضور',
    selectWeekToEdit: 'اختر أسبوعاً لتعديل الحضور',
    quickMarkAll: 'تحديد الكل بسرعة:',
    studentName: 'اسم الطالب',
    presentP: 'حاضر (P)',
    absentA: 'غائب (A)',
    lateL: 'متأخر (L)',
    permissionE: 'إذن (E)',
    failedToFetchClasses: 'فشل في جلب الفصول',
    pleaseSelectClassAndWeek: 'يرجى اختيار الفصل وتاريخ بداية الأسبوع',
    noAttendanceDataToSave: 'لا توجد بيانات حضور للحفظ',
    failedToCreateAttendance: 'فشل في إنشاء الحضور',
    failedToSaveAttendance: 'فشل في حفظ الحضور'
  },
  fr: {
    dashboard: 'Tableau de bord',
    registration: 'Inscription',
    registerStudent: 'Inscrire un étudiant',
    registerStaff: 'Inscrire un personnel',
    lists: 'Listes',
    students: 'Étudiants',
    staff: 'Personnel',
    academic: 'Académique',
    evaluation: 'Évaluation',
    markLists: 'Listes de notes',
    attendance: 'Présence',
    createMarklist: 'Créer une liste de notes',
    reportCard: 'Bulletin',
    schedule: 'Emploi du temps',
    post: 'Publication',
    tasks: 'Tableau des tâches',
    administration: 'Administration',
    communication: 'Communication',
    payments: 'Paiements',
    settings: 'Paramètres',
    search: 'Rechercher...',
    myProfile: 'Mon profil',
    logout: 'Déconnexion',
    settingsTitle: 'Paramètres',
    settingsSubtitle: 'Gérez votre compte et les préférences de l\'application',
    profile: 'Profil',
    password: 'Mot de passe',
    theme: 'Thème',
    language: 'Langue',
    branding: 'Image de marque',
    profileSettings: 'Paramètres du profil',
    fullName: 'Nom complet',
    emailAddress: 'Adresse e-mail',
    saveProfile: 'Enregistrer le profil',
    changePassword: 'Changer le mot de passe',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer le nouveau mot de passe',
    themeSettings: 'Paramètres du thème',
    darkMode: 'Mode sombre',
    colorPresets: 'Couleurs prédéfinies',
    customColors: 'Couleurs personnalisées',
    primaryColor: 'Couleur principale',
    secondaryColor: 'Couleur secondaire',
    preview: 'Aperçu',
    saveTheme: 'Enregistrer le thème',
    languageSettings: 'Paramètres de langue',
    brandingSettings: 'Paramètres de marque',
    websiteIcon: 'Icône du site',
    uploadIcon: 'Télécharger l\'icône',
    save: 'Enregistrer',
    cancel: 'Annuler',
    loading: 'Chargement...',
    success: 'Succès',
    error: 'Erreur',
    delete: 'Supprimer',
    edit: 'Modifier',
    view: 'Voir',
    refresh: 'Actualiser',
    previous: 'Précédent',
    next: 'Suivant',
    page: 'Page',
    of: 'sur',
    all: 'Tous',
    noDataFound: 'Aucune donnée trouvée',
    actions: 'Actions',
    // List Pages
    studentDirectory: 'Répertoire des étudiants',
    studentDirectoryDesc: 'Gérer tous les étudiants et leurs documents',
    staffDirectory: 'Répertoire du personnel',
    staffDirectoryDesc: 'Gérer tout le personnel et leurs documents',
    searchByName: 'Rechercher par nom...',
    searchStudents: 'Rechercher par nom, tuteur, téléphone...',
    searchStaff: 'Rechercher par nom, e-mail, téléphone...',
    allGenders: 'Tous les genres',
    male: 'Masculin',
    female: 'Féminin',
    allTypes: 'Tous les types',
    totalStaff: 'Personnel total',
    categories: 'Catégories',
    classes: 'Classes',
    noStudentsFound: 'Aucun étudiant trouvé',
    noStaffFound: 'Aucun personnel trouvé',
    tryAdjustingFilters: 'Essayez d\'ajuster votre recherche ou vos filtres',
    documents: 'Documents',
    document: 'Document',
    basicInformation: 'Informations de base',
    loginCredentials: 'Identifiants de connexion',
    studentAccount: 'Compte étudiant',
    guardianAccount: 'Compte tuteur',
    username: 'Nom d\'utilisateur',
    documentsAndFiles: 'Documents et fichiers',
    download: 'Télécharger',
    age: 'Âge',
    guardian: 'Tuteur',
    phone: 'Téléphone',
    email: 'E-mail',
    role: 'Rôle',
    department: 'Département',
    employmentType: 'Type d\'emploi',
    fullTime: 'Temps plein',
    partTime: 'Temps partiel',
    // Schedule
    scheduleDashboard: 'Tableau de bord des horaires',
    scheduleDesc: 'Gérer les emplois du temps des classes',
    timetable: 'Emploi du temps',
    createSchedule: 'Créer un horaire',
    viewSchedule: 'Voir l\'horaire',
    // Mark List
    markListView: 'Vue des notes',
    markListDesc: 'Voir et gérer les notes des étudiants',
    subject: 'Matière',
    marks: 'Notes',
    grade: 'Note',
    total: 'Total',
    average: 'Moyenne',
    // Evaluation
    evaluationTitle: 'Évaluation',
    evaluationDesc: 'Évaluer les performances des étudiants',
    // Attendance
    attendanceView: 'Vue de présence',
    attendanceDesc: 'Suivre la présence des étudiants',
    present: 'Présent',
    absent: 'Absent',
    late: 'En retard',
    // Communication
    communicationTitle: 'Communication',
    communicationDesc: 'Envoyer des messages et des annonces',
    sendMessage: 'Envoyer un message',
    announcements: 'Annonces',
    // Profile Pages
    posts: 'Publications',
    evaluations: 'Évaluations',
    messages: 'Messages',
    profileInformation: 'Informations du profil',
    accountInformation: 'Informations du compte',
    back: 'Retour',
    fillForm: 'Remplir le formulaire',
    viewReport: 'Voir le rapport',
    inProgress: 'En cours',
    noEvaluations: 'Aucune évaluation assignée',
    noPosts: 'Aucune publication',
    noMessages: 'Aucun message',
    // Attendance specific
    markAttendance: 'Marquer la présence',
    viewAttendanceMode: 'Voir la présence',
    permission: 'Permission',
    saveAttendance: 'Enregistrer la présence',
    createWeek: 'Créer une semaine',
    selectWeek: 'Sélectionner la semaine',
    currentWeek: 'Semaine actuelle',
    nextWeek: 'Semaine prochaine',
    // Guardian/Ward specific
    wards: 'Enfants',
    selectWard: 'Sélectionner l\'enfant',
    wardAttendance: 'Présence de l\'enfant',
    selectPeriod: 'Sélectionner la période',
    attendanceRecord: 'Registre de présence',
    // Class/Teacher specific
    classComm: 'Classe',
    marklist: 'Liste de notes',
    mySchedule: 'Mon emploi du temps',
    // Dark mode
    darkModeOn: 'Mode sombre activé',
    darkModeOff: 'Mode sombre désactivé',
    settingsInfo: 'Vos préférences sont enregistrées automatiquement et seront mémorisées lors de votre prochaine connexion.',
    // Navigation - Additional
    evaluationBook: 'Carnet d\'évaluation',
    evalBookReports: 'Rapports du carnet d\'évaluation',
    evalBookAssignments: 'Affectations du carnet d\'évaluation',
    subAccounts: 'Sous-comptes',
    classTeachers: 'Enseignants de classe',
    // Guardian Directory
    guardianDirectory: 'Répertoire des tuteurs',
    guardianDirectoryDesc: 'Voir et gérer tous les tuteurs',
    guardians: 'Tuteurs',
    searchGuardians: 'Rechercher des tuteurs...',
    noGuardiansFound: 'Aucun tuteur trouvé',
    associatedStudents: 'Étudiants associés',
    contactInformation: 'Informations de contact',
    relation: 'Relation',
    // Evaluation Book
    evaluationInbox: 'Boîte de réception des évaluations',
    evaluationInboxDesc: 'Consultez et répondez aux évaluations quotidiennes de votre enfant',
    pendingResponse: 'En attente de réponse',
    responded: 'Répondu',
    noEvaluationsYet: 'Aucune évaluation',
    noEvaluationsDesc: 'Vous n\'avez aucune évaluation à consulter pour le moment.',
    tapToAddFeedback: 'Appuyez pour ajouter votre commentaire',
    allWards: 'Tous les enfants',
    // Evaluation Book Reports
    evaluationBookReports: 'Rapports du carnet d\'évaluation',
    evaluationBookReportsDesc: 'Voir tous les rapports d\'évaluation de l\'école',
    totalEvaluations: 'Total des évaluations',
    pendingResponses: 'Réponses en attente',
    responseRate: 'Taux de réponse',
    filters: 'Filtres',
    startDate: 'Date de début',
    endDate: 'Date de fin',
    allClasses: 'Toutes les classes',
    searchStudent: 'Rechercher un étudiant...',
    clearFilters: 'Effacer les filtres',
    noReportsFound: 'Aucun rapport trouvé',
    adjustFiltersOrWait: 'Ajustez vos filtres ou attendez que des évaluations soient créées',
    evaluationData: 'Données d\'évaluation',
    guardianFeedback: 'Commentaire du tuteur',
    submitted: 'Soumis',
    // Teacher Assignment
    teacherAssignments: 'Affectations des enseignants',
    teacherAssignmentsDesc: 'Affecter des enseignants aux classes pour le système de carnet d\'évaluation',
    newAssignment: 'Nouvelle affectation',
    selectTeacher: 'Sélectionner un enseignant...',
    selectClass: 'Sélectionner une classe...',
    assignTeacher: 'Affecter l\'enseignant',
    assigning: 'Affectation en cours...',
    teacherAssignedSuccess: 'Enseignant affecté avec succès',
    assignmentRemoved: 'Affectation supprimée',
    removeAssignment: 'Supprimer cette affectation?',
    noAssignmentsYet: 'Aucune affectation pour le moment',
    assignTeachersAbove: 'Affectez des enseignants aux classes en utilisant le formulaire ci-dessus',
    teacherCount: 'enseignant(s)',
    // Class Teacher Assignment
    classTeacherAssignment: 'Affectation de l\'enseignant de classe',
    classTeacherAssignmentDesc: 'Affecter des enseignants aux classes pour la gestion des présences',
    assignClassTeacher: 'Affecter l\'enseignant de classe',
    selectTeacherLabel: 'Sélectionner l\'enseignant:',
    selectClassLabel: 'Sélectionner la classe:',
    assign: 'Affecter',
    currentAssignments: 'Affectations actuelles',
    noClassTeachersAssigned: 'Aucun enseignant de classe affecté',
    removeClassTeacher: 'Retirer l\'enseignant de classe de',
    teacherUnassigned: 'Enseignant retiré de',
    assigned: 'Affecté',
    unassignedClasses: 'Classes non affectées',
    // Create Attendance
    createAttendance: 'Créer la présence',
    createAttendanceDesc: 'Créer et gérer la présence pour n\'importe quelle classe',
    createNewWeek: 'Créer une nouvelle semaine',
    editExisting: 'Modifier l\'existant',
    classLabel: 'Classe:',
    weekStartMonday: 'Début de semaine (Lundi):',
    selectWeekLabel: 'Sélectionner la semaine:',
    selectWeekOption: '-- Sélectionner la semaine --',
    createAttendanceBtn: 'Créer la présence',
    saveAttendanceBtn: 'Enregistrer la présence',
    existingAttendanceWeeks: 'Semaines de présence existantes pour',
    loadingAttendanceData: 'Chargement des données de présence...',
    noAttendanceData: 'Aucune donnée de présence',
    selectWeekToEdit: 'Sélectionnez une semaine pour modifier la présence',
    quickMarkAll: 'Marquer tout rapidement:',
    studentName: 'Nom de l\'étudiant',
    presentP: 'Présent (P)',
    absentA: 'Absent (A)',
    lateL: 'En retard (L)',
    permissionE: 'Permission (E)',
    failedToFetchClasses: 'Échec du chargement des classes',
    pleaseSelectClassAndWeek: 'Veuillez sélectionner une classe et une date de début de semaine',
    noAttendanceDataToSave: 'Aucune donnée de présence à enregistrer',
    failedToCreateAttendance: 'Échec de la création de la présence',
    failedToSaveAttendance: 'Échec de l\'enregistrement de la présence'
  }
};

const AppContext = createContext();

// Alkhwarizm Brand Color System
const DEFAULT_THEME = {
  primaryColor: '#6F56FF',    // Digital Violet - Main identity color
  secondaryColor: '#8FA2FF',  // Soft Indigo - Hover states, secondary buttons
  mode: 'light'
};

// Helper function to update favicon
const updateFavicon = (iconUrl) => {
  // Update standard favicon
  let link = document.querySelector("link[rel*='icon']");
  if (!link) {
    link = document.createElement('link');
    link.rel = 'shortcut icon';
    document.getElementsByTagName('head')[0].appendChild(link);
  }
  link.type = 'image/x-icon';
  link.href = iconUrl;
  
  // Update apple touch icon
  let appleLink = document.querySelector("link[rel='apple-touch-icon']");
  if (!appleLink) {
    appleLink = document.createElement('link');
    appleLink.rel = 'apple-touch-icon';
    document.getElementsByTagName('head')[0].appendChild(appleLink);
  }
  appleLink.href = iconUrl;
};

// Helper function to update manifest icons dynamically
const updateManifestIcons = (iconUrl) => {
  try {
    // Get the manifest link element
    let manifestLink = document.querySelector("link[rel='manifest']");
    if (!manifestLink) {
      manifestLink = document.createElement('link');
      manifestLink.rel = 'manifest';
      document.getElementsByTagName('head')[0].appendChild(manifestLink);
    }
    
    // Create a dynamic manifest with the custom icon
    const manifest = {
      short_name: "Skoolific",
      name: "Skoolific School Management",
      icons: [
        {
          src: iconUrl,
          sizes: "192x192",
          type: "image/png"
        },
        {
          src: iconUrl,
          sizes: "512x512",
          type: "image/png"
        }
      ],
      start_url: "/",
      display: "standalone",
      theme_color: "#667eea",
      background_color: "#ffffff",
      orientation: "portrait"
    };
    
    // Convert manifest to blob and create object URL
    const manifestBlob = new Blob([JSON.stringify(manifest)], { type: 'application/json' });
    const manifestURL = URL.createObjectURL(manifestBlob);
    manifestLink.href = manifestURL;
  } catch (error) {
    console.error('Error updating manifest:', error);
  }
};

export const AppProvider = ({ children }) => {
  const [theme, setTheme] = useState(DEFAULT_THEME);
  
  const [language, setLanguage] = useState('en');
  
  const [profile, setProfile] = useState({
    name: 'Administrator',
    email: '',
    profileImage: null
  });

  const [websiteName, setWebsiteName] = useState('School Management System');

  // Load saved settings on mount - prioritize database over localStorage
  useEffect(() => {
    const loadSettings = async () => {
      // First load from localStorage for immediate display
      const savedTheme = localStorage.getItem('appTheme');
      const savedLanguage = localStorage.getItem('appLanguage');
      const savedProfile = localStorage.getItem('adminUser');
      const savedProfileImage = localStorage.getItem('profileImage');

      if (savedTheme) {
        const parsedTheme = JSON.parse(savedTheme);
        setTheme(parsedTheme);
        applyTheme(parsedTheme);
      }
      
      if (savedLanguage) {
        setLanguage(savedLanguage);
        applyLanguageDirection(savedLanguage);
      }
      
      if (savedProfile) {
        const user = JSON.parse(savedProfile);
        setProfile(prev => ({
          ...prev,
          name: user.name || 'Administrator',
          email: user.email || ''
        }));
      }
      
      if (savedProfileImage) {
        setProfile(prev => ({ ...prev, profileImage: savedProfileImage }));
      }

      // Then load branding from database (this overrides localStorage)
      try {
        const response = await axios.get(`${import.meta.env.VITE_API_URL}/settings/branding`);
        const data = response.data;
        
        // Update website name from database
        if (data.website_name) {
          setWebsiteName(data.website_name);
          document.title = data.website_name;
        }
        
        // Update theme from database
        if (data.primary_color || data.secondary_color) {
          const dbTheme = {
            primaryColor: data.primary_color || DEFAULT_THEME.primaryColor,
            secondaryColor: data.secondary_color || DEFAULT_THEME.secondaryColor,
            mode: data.theme_mode || 'light'
          };
          setTheme(dbTheme);
          applyTheme(dbTheme);
          localStorage.setItem('appTheme', JSON.stringify(dbTheme));
        }
        
        // Update favicon from database or use default Skoolific icon
        const iconUrl = data.website_icon 
          ? `${import.meta.env.VITE_API_URL.replace('/api', '')}/uploads/branding/${data.website_icon}`
          : '/skoolific-icon.png';
        
        // Update all icon links
        updateFavicon(iconUrl);
        updateManifestIcons(iconUrl);
      } catch (error) {
        console.log('Could not load branding from database, using localStorage');
        // Fallback to localStorage for website name
        const savedWebsiteName = localStorage.getItem('websiteName');
        if (savedWebsiteName) {
          setWebsiteName(savedWebsiteName);
          document.title = savedWebsiteName;
        }
        
        // Always set default Skoolific icon as fallback
        updateFavicon('/skoolific-icon.png');
        updateManifestIcons('/skoolific-icon.png');
      }
    };
    
    loadSettings();
  }, []);

  const applyTheme = (themeData) => {
    // Set primary and secondary colors
    document.documentElement.style.setProperty('--primary-color', themeData.primaryColor);
    document.documentElement.style.setProperty('--secondary-color', themeData.secondaryColor);
    
    // Calculate and set computed color variables based on primary color
    const primaryRgb = hexToRgb(themeData.primaryColor);
    if (primaryRgb) {
      const { r, g, b } = primaryRgb;
      document.documentElement.style.setProperty('--primary-light', `rgba(${r}, ${g}, ${b}, 0.1)`);
      document.documentElement.style.setProperty('--primary-lighter', `rgba(${r}, ${g}, ${b}, 0.05)`);
      document.documentElement.style.setProperty('--primary-shadow', `rgba(${r}, ${g}, ${b}, 0.3)`);
      document.documentElement.style.setProperty('--primary-shadow-lg', `rgba(${r}, ${g}, ${b}, 0.35)`);
    }
    
    // Apply dark mode - set both class and data-theme attribute
    if (themeData.mode === 'dark') {
      document.body.classList.add('dark-mode');
      document.documentElement.setAttribute('data-theme', 'dark');
    } else {
      document.body.classList.remove('dark-mode');
      document.documentElement.setAttribute('data-theme', 'light');
    }
  };

  const applyLanguageDirection = (lang) => {
    if (lang === 'ar') {
      document.documentElement.dir = 'rtl';
      document.body.classList.add('rtl');
    } else {
      document.documentElement.dir = 'ltr';
      document.body.classList.remove('rtl');
    }
  };

  const updateTheme = (newTheme) => {
    setTheme(newTheme);
    applyTheme(newTheme);
    localStorage.setItem('appTheme', JSON.stringify(newTheme));
  };

  const updateLanguage = (lang) => {
    setLanguage(lang);
    applyLanguageDirection(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const updateProfile = (newProfile) => {
    setProfile(prev => ({ ...prev, ...newProfile }));
    
    // Update adminUser in localStorage
    const adminUser = JSON.parse(localStorage.getItem('adminUser') || '{}');
    adminUser.name = newProfile.name || profile.name;
    adminUser.email = newProfile.email || profile.email;
    localStorage.setItem('adminUser', JSON.stringify(adminUser));
    
    if (newProfile.profileImage) {
      localStorage.setItem('profileImage', newProfile.profileImage);
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  const updateWebsiteName = (name) => {
    setWebsiteName(name);
    localStorage.setItem('websiteName', name);
    document.title = name;
  };

  return (
    <AppContext.Provider value={{
      theme,
      updateTheme,
      language,
      updateLanguage,
      profile,
      updateProfile,
      websiteName,
      updateWebsiteName,
      t,
      translations
    }}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
};

export default AppContext;
